import {test} from 'node:test';import assert from 'node:assert/strict';
import {seed,effective,transition,status,validateCSV,can,fieldAccess,cents} from '../src/domain.js';
test('regular amendments require finance plus superuser approvals',()=>{const s=seed(),a=s.amendments[2];a.createdBy='u2';a.creatorSuperuser=false;transition(s,s.users[2],'t1',a.id,'review');transition(s,s.users[2],'t1',a.id,'approve');assert.equal(status(s,a),'Superuser approval');assert.equal(effective(s,s.orders[2]),32000000);assert.throws(()=>transition(s,s.users[2],'t1',a.id,'approve'));transition(s,s.users[0],'t1',a.id,'approve');assert.equal(effective(s,s.orders[2]),30000000);assert.equal(status(s,a),'Approved');});
test('creator cannot approve and project identity is enforced',()=>{const s=seed();s.amendments.find(a=>a.id==='a2').createdBy='u2';s.amendments.find(a=>a.id==='a2').creatorSuperuser=false;assert.throws(()=>transition(s,s.users[1],'t1','a2','approve'),/creator/);assert.throws(()=>transition(s,s.users[2],'t2','a2','approve'),/not found/);assert.equal(can(s,s.users[3],'t1','amend'),false);assert.equal(fieldAccess(s,s.users[3],'t1','amount'),'hidden');});
test('CSV catches all row errors and computes sequential totals',()=>{const s=seed();const v=validateCSV(s,s.users[0],'t1','work_order,delta_including_tax,reason\nWO-SKY-001,200000,Add\nWO-SKY-002,-9999999,Remove');assert.equal(v.errors.length,1);assert.equal(v.errors[0].row,3);const good=validateCSV(s,s.users[0],'t1','work_order,delta_including_tax,reason\nWO-SKY-001,200000,Add\nWO-SKY-001,-100000,Reduce');assert.equal(good.rows[1].next,150000000);});
test('approval revalidates against changes since import',()=>{const s=seed(),o=s.orders[2],a=s.amendments[2];o.base=1000000;assert.throws(()=>transition(s,s.users[0],'t1',a.id,'approve'),/below zero/);});
test('exact decimal inputs reject excess precision',()=>{assert.equal(cents('-0.01'),-1);assert.equal(cents('200000'),20000000);assert.throws(()=>cents('1.234'));assert.throws(()=>cents('1e9'));});

test('superuser approves their own pending submissions directly without finance or review',()=>{const s=seed();for(const a of s.amendments.filter(a=>a.approvalPolicy===2)){transition(s,s.users[0],'t1',a.id,'approve');assert.equal(status(s,a),'Approved');assert.equal(s.events.filter(e=>e.amendmentId===a.id&&e.stage==='superuser').length,1);assert.throws(()=>transition(s,s.users[0],'t1',a.id,'approve'));}assert.equal(effective(s,s.orders[1]),55000000);});
test('Admin is distinct from manager and either approval order completes the regular pair',()=>{for(const first of ['admin','superuser']){const s=seed(),a=s.amendments[2];a.createdBy='u3';a.creatorSuperuser=false;assert.throws(()=>transition(s,s.users[1],'t1',a.id,'approve'));s.memberships.find(m=>m.userId==='u2'&&m.tenantId==='t1').roleIds=['admin'];transition(s,s.users[1],'t1',a.id,'review');const actors=first==='admin'?[s.users[1],s.users[0]]:[s.users[0],s.users[1]];transition(s,actors[0],'t1',a.id,'approve');assert.notEqual(status(s,a),'Approved');transition(s,actors[1],'t1',a.id,'approve');assert.equal(status(s,a),'Approved');}});
test('admin + finance without superuser cannot finalize, and a dual role cannot approve twice',()=>{const s=seed(),a=s.amendments[2];a.createdBy='u4';a.creatorSuperuser=false;s.memberships.find(m=>m.userId==='u2'&&m.tenantId==='t1').roleIds=['admin','finance'];transition(s,s.users[1],'t1',a.id,'review');transition(s,s.users[1],'t1',a.id,'approve');assert.throws(()=>transition(s,s.users[2],'t1',a.id,'approve'));assert.throws(()=>transition(s,s.users[1],'t1',a.id,'approve'));assert.equal(status(s,a),'Superuser approval');assert.equal(effective(s,s.orders[2]),32000000);});
test('approval stage and action must come from the same project role',()=>{const s=seed(),a=s.amendments[2];a.createdBy='u4';a.creatorSuperuser=false;s.memberships.find(m=>m.userId==='u2'&&m.tenantId==='t1').roleIds=['admin','manager'];s.roles.find(r=>r.id==='admin').permissions.work_order.actions=['view'];transition(s,s.users[1],'t1',a.id,'review');assert.throws(()=>transition(s,s.users[1],'t1',a.id,'approve'));});

test('work-order items use exact quantities and dated periods with an approved project PO reference',async()=>{const {workDetails,redactWorkDetails}=await import('../src/work-items.js');const s=seed(),u=s.users[0],p=s.purchaseOrders[0];const d={base:126,purchaseOrderId:p.id,items:[{description:'Cable installation',unit:'metre',quantityMilli:1250,rate:101,startDate:'2026-10-01',endDate:'2026-10-31'}]};assert.throws(()=>workDetails(s,u,'t1',d),/approved purchase order/);s.purchaseEvents=[{id:'pe1',purchaseOrderId:p.id,action:'approve',stage:'superuser',actorId:'u1'}];let v=workDetails(s,u,'t1',d);assert.equal(v.items[0].amount,126);assert.equal(v.purchaseOrderNumber,'PO-SKY-001');assert.equal(v.purchaseOrderDate,'2026-10-05');assert.throws(()=>workDetails(s,u,'t2',d),/approved purchase/);assert.throws(()=>workDetails(s,u,'t1',{...d,base:127}),/equal/);assert.throws(()=>workDetails(s,u,'t1',{...d,items:[{...d.items[0],endDate:'2026-09-30'}]}),/start\/end/);assert.throws(()=>workDetails(s,u,'t1',{...d,items:[{...d.items[0],startDate:'2026-02-30'}]}),/valid/);const o={...v,tenantId:'t1'};redactWorkDetails(s,s.users[3],o);assert.equal(o.items[0].rate,undefined);assert.equal(o.items[0].amount,undefined);assert.equal(o.items[0].quantityMilli,1250);assert.equal(o.items[0].unit,'metre');});
