import {PGlite} from '@electric-sql/pglite';import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';import {readFileSync,readdirSync} from 'node:fs';import assert from 'node:assert/strict';import {test} from 'node:test';import {seed} from '../src/domain.js';import {buildSchedule} from '../src/payment-schedules.js';
test('SQL protects global bank numbers, schedules, due snapshots, settlement caps and paired approvals',async()=>{
 const db=new PGlite({extensions:{pgcrypto}});await db.waitReady;const root=new URL('../migrations/',import.meta.url);for(const f of readdirSync(root).filter(f=>f.endsWith('.sql')).sort())await db.exec('BEGIN;'+readFileSync(new URL(f,root),'utf8')+'COMMIT;');
 await db.exec('CREATE ROLE payment_app;GRANT USAGE ON SCHEMA public TO payment_app;GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA public TO payment_app;SET ROLE payment_app;');
 const actor=u=>db.query("SELECT set_config('app.user_id',$1,false)",[u]);const save=async(id,k,body,u='u1',t='t1')=>{await actor(u);return db.query('INSERT INTO erp_extensions(id,tenant_id,kind,body) VALUES($1,$2,$3,$4)',[id,t,k,JSON.stringify({formVersion:1,data:{},...body})])};const ev=async(id,a,u='u1',stage='')=>{await actor(u);return db.query('INSERT INTO erp_extension_events VALUES($1,$2,$3,$4,$5,$6)',[id+a+u,id,a,stage,u,'{}'])};const body=async id=>(await db.query('SELECT body FROM erp_extensions WHERE id=$1',[id])).rows[0]?.body;
 const bank={number:'001234567890',bank:'Example Bank',ifsc:'HDFC0001234',label:'Payroll',active:true};await save('corporate-sql','corporate_account',bank);await assert.rejects(save('repeat','corporate_account',bank,'u1','t2'),/duplicate/);const rera=(await db.query('SELECT * FROM rera_accounts WHERE tenant_id=$1 LIMIT 1',['t1'])).rows[0];await assert.rejects(save('repeat-rera','corporate_account',{...bank,number:rera.number}),/duplicate/);await actor('u1');await assert.rejects(db.query("INSERT INTO rera_accounts VALUES('duplicate-corporate','t2',$1,$2)",[bank.number,JSON.stringify({...bank,tenantId:'t2'})]),/duplicate/);await assert.rejects(save('not-su','corporate_account',{...bank,number:'001234567891'},'u3'),/permission|action/i);await actor('u1');await assert.rejects(db.exec("UPDATE erp_extensions SET body=body||'{\"active\":false}' WHERE id='corporate-sql'"),/active/);
 await db.exec("INSERT INTO finance_documents(id,kind,tenant_id,amount,expense_date,form_version,created_by,body) VALUES('salary-sql','expense','t1',100000,'2026-10-01',1,'u1','{\"description\":\"Payroll\",\"category\":\"Salaries\",\"payee\":\"Sample staff\"}');INSERT INTO finance_events VALUES('salary-submit','salary-sql','submit','','u1','{}'),('salary-approve','salary-sql','approve','superuser','u1','{}');");
 const pay={expenseId:'salary-sql',accountId:'corporate-sql',paid:90000,tds:10000,paidDate:'2026-10-06',reference:'PAY-SQL'};await save('pay-sql','corporate_payment',pay,'u3');assert.equal((await body('pay-sql')).creatorSuperuser,false);await ev('pay-sql','submit','u3');await assert.rejects(ev('pay-sql','approve','u1','superuser'),/Review/);await ev('pay-sql','review','u1');await ev('pay-sql','approve','u1','superuser');assert.equal((await db.query("SELECT extension_approved('pay-sql') ok")).rows[0].ok,false);await db.exec("INSERT INTO membership_roles VALUES('t1','u2','admin')");await ev('pay-sql','approve','u2','admin');assert.equal((await db.query("SELECT extension_approved('pay-sql') ok")).rows[0].ok,true);await assert.rejects(save('overpay','corporate_payment',{...pay,reference:'PAY-OVER',paid:1,tds:0}),/settlement/);
 await actor('u1');await db.query("INSERT INTO operational_records(id,tenant_id,kind,form_id,form_version,created_by,body) VALUES('sale-schedule','t1','sale','sale',1,'u1',$1)",[JSON.stringify({unit:'C-301',customer:'Sample customer',status:'Booked',amount:1050000,date:'2026-10-01',data:{}})]);
 const booking={saleId:'sale-schedule',unit:'C-301',wing:'C',bookingDate:'2026-10-01',details:{applicant:{fullName:'Sample customer',phone:'9000000001',email:'buyer@example.com'}},pricing:{gstBps:500,tdsBps:100,partA:[{label:'Sale value',amount:1000000}],partB:[]}};await save('booking-sql','booking',booking);const template=(await body('reference-schedule-t1'));const snapshot=buildSchedule(booking,template);await assert.rejects(save('forged-schedule','payment_schedule',{bookingId:'booking-sql',templateId:template.id,...snapshot,rows:snapshot.rows.map((r,i)=>({...r,gross:r.gross+(i===0?1:i===1?-1:0)}))}),/Schedule amounts/);await save('schedule-sql','payment_schedule',{bookingId:'booking-sql',templateId:template.id,...snapshot});await assert.rejects(db.exec("UPDATE operational_records SET body=body||'{\"amount\":1}' WHERE id='sale-schedule'"),/retained/);
 const demand={scheduleId:'schedule-sql',code:'excavation',accountId:rera.id,number:'DEM-SQL',gross:1,dueDate:'2099-01-01'};await assert.rejects(save('no-milestone','demand',demand),/completion/);await save('exc-sql','milestone',{code:'excavation',wing:'C',date:'2026-10-01',note:'Certified completion'});await save('demand-sql','demand',demand,'u3');const d=await body('demand-sql');assert.equal(d.dueDate,'2026-10-16');assert.equal(d.gross,52500);assert.equal(d.bank.number,rera.number);await ev('demand-sql','submit','u3');await ev('demand-sql','review','u1');await ev('demand-sql','approve','u1','superuser');await ev('demand-sql','approve','u2','admin');await save('corrected','milestone',{code:'excavation',wing:'C',date:'2026-10-03',note:'Corrected completion'});assert.equal((await body('demand-sql')).dueDate,'2026-10-16');await assert.rejects(save('second-demand','demand',{...demand,number:'DEM-SECOND'}),/active demand/i);
 await actor('u1');await db.query("INSERT INTO operational_records(id,tenant_id,kind,form_id,form_version,created_by,body) VALUES('receipt-schedule','t1','collection','collection',1,'u1',$1)",[JSON.stringify({saleId:'sale-schedule',amount:52000,tds:500,date:'2026-10-06',reference:'RC-SCHEDULE',data:{}})]);await save('allocation-sql','receipt_allocation',{receiptId:'receipt-schedule',demandId:d.id,amount:52500,tds:500});await assert.rejects(save('over-allocation','receipt_allocation',{receiptId:'receipt-schedule',demandId:d.id,amount:1,tds:0}),/balance/);await assert.rejects(db.exec("UPDATE erp_extensions SET body=body||'{\"gross\":1}' WHERE id='demand-sql'"),/history/);await actor('u5');assert.equal((await db.query("SELECT id FROM erp_extensions WHERE kind<>'corporate_account' AND tenant_id='t1'")).rows.length,0);await assert.rejects(save('cross-booking','booking',booking,'u5','t2'),/sale|permission|action/i);await db.close();
});
