import {PGlite} from '@electric-sql/pglite';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {test} from 'node:test';
test('PostgreSQL financial and tenant rules',async()=>{
const db=new PGlite({extensions:{pgcrypto}});await db.waitReady;
const root=new URL('../',import.meta.url).pathname;
await db.exec('BEGIN;'+readFileSync(root+'migrations/001_schema.sql','utf8')+readFileSync(root+'migrations/002_demo_seed.sql','utf8')+readFileSync(root+'migrations/003_vendors_users_superuser.sql','utf8')+'COMMIT;');
// Apply the new migration to an already-committed existing installation.
await db.exec('BEGIN;'+readFileSync(root+'migrations/004_projects_procurement_inventory.sql','utf8')+readFileSync(root+'migrations/005_role_management.sql','utf8')+readFileSync(root+'migrations/006_document_fields.sql','utf8')+'COMMIT;');
assert.equal((await db.query("SELECT effective_total('w1') total")).rows[0].total,140000000);
assert.equal((await db.query("SELECT effective_total('w2') total")).rows[0].total,48500000);
await assert.rejects(db.exec("UPDATE work_orders SET base=0 WHERE id='w1'"),/immutable/);
await assert.rejects(db.exec("INSERT INTO rera_accounts VALUES('duplicate','t2','501008742631','{}')"),/duplicate/);
await assert.rejects(db.exec("INSERT INTO amendment_events VALUES('bad','a3','approve','finance','u3','{}')"),/Review is required/);
await db.exec("CREATE ROLE ledger_app;GRANT USAGE ON SCHEMA public TO ledger_app; GRANT SELECT ON ALL TABLES IN SCHEMA public TO ledger_app; GRANT INSERT ON amendment_events TO ledger_app;");
await db.exec("SET ROLE ledger_app; SELECT set_config('app.user_id','u4',false);");
assert.equal((await db.query('SELECT count(*) n FROM tenants')).rows[0].n,2);
assert.equal((await db.query("SELECT count(*) n FROM tenants WHERE id='t3'")).rows[0].n,0);
await db.exec("SELECT set_config('app.user_id','u2',false);");
await db.exec("INSERT INTO amendment_events VALUES('review3','a3','review','','u2','{}'); INSERT INTO amendment_events VALUES('manager3','a3','approve','manager','u2','{}');");
await assert.rejects(db.exec("INSERT INTO amendment_events VALUES('self2','a3','approve','finance','u2','{}')"),/duplicate/);
await db.exec("SELECT set_config('app.user_id','u3',false); INSERT INTO amendment_events VALUES('finance3','a3','approve','finance','u3','{}');");
assert.equal((await db.query("SELECT effective_total('w3') total")).rows[0].total,30000000);
await assert.rejects(db.exec("INSERT INTO amendment_events VALUES('again','a3','reject','','u2','{}')"),/already finalized/);
await db.exec("SELECT set_config('app.user_id','u1',false); INSERT INTO amendment_events VALUES('admin-finance','a2','approve','finance','u1','{}');");
assert.equal((await db.query("SELECT effective_total('w2') total")).rows[0].total,55000000);
await db.exec("RESET ROLE; INSERT INTO vendors VALUES('repeat','t3',false,'{\"name\":\"Sri Sai Constructions\"}');");
assert.equal((await db.query("SELECT count(*) n FROM vendors WHERE body->>'name'='Sri Sai Constructions'")).rows[0].n,3);
await assert.rejects(db.exec("INSERT INTO work_order_vendors VALUES('w1','t1','v6','{}')"),/foreign key|duplicate/);
await assert.rejects(db.exec("UPDATE work_order_vendors SET snapshot='{}' WHERE order_id='w1'"),/immutable/);
await db.exec("GRANT INSERT ON users TO ledger_app;GRANT UPDATE(password_hash) ON users TO ledger_app;SET ROLE ledger_app; SELECT set_config('app.user_id','u4',false);");
await assert.rejects(db.exec("INSERT INTO users(id,name,title,superuser,password_hash,username) VALUES('bad-user','Bad','x',false,'hash','bad-user')"),/row-level security/);
await db.exec("SELECT set_config('app.user_id','u1',false); INSERT INTO users(id,name,title,superuser,password_hash,username) VALUES('new-user','New','Engineer',false,crypt('secret-example',gen_salt('bf')),'new-user');");
assert.equal((await db.query("SELECT password_hash=crypt('secret-example',password_hash) ok FROM users WHERE id='new-user'")).rows[0].ok,true);
await assert.rejects(db.exec("INSERT INTO users(id,name,title,superuser,password_hash,username) VALUES('duplicate-user','D','x',false,'hash','NEW-USER')"),/duplicate/);
await assert.rejects(db.exec("INSERT INTO users(id,name,title,superuser,password_hash,username) VALUES('privilege-user','D','x',true,'hash','privilege-user')"),/row-level security/);
// Project management and purchase/inventory invariants run under the application role.
await db.exec("RESET ROLE; GRANT INSERT,UPDATE ON tenants TO ledger_app; GRANT SELECT,INSERT,UPDATE ON purchase_orders TO ledger_app; GRANT SELECT,INSERT ON purchase_events,stock_lots,stock_movements TO ledger_app; SET ROLE ledger_app; SELECT set_config('app.user_id','u4',false);");
assert.equal((await db.query("UPDATE tenants SET code='FORBIDDEN' WHERE id='t1' RETURNING id")).rows.length,0);
await assert.rejects(db.exec("INSERT INTO tenants(id,code,body) VALUES('bad-project','BAD','{}')"),/row-level security/);
await db.exec("SELECT set_config('app.user_id','u1',false); UPDATE tenants SET code='SKY-EDIT' WHERE id='t1';");
assert.equal((await db.query("SELECT code FROM tenants WHERE id='t1'")).rows[0].code,'SKY-EDIT');
assert.equal((await db.query("SELECT purchase_approved('po1') ok")).rows[0].ok,false);
await assert.rejects(db.exec("INSERT INTO stock_lots VALUES('lot-early','po1','t1','pl1','{}')"),/approved purchased/);
await db.exec("INSERT INTO purchase_events VALUES('po-submit','po1','submit','','u1','{}');");
await assert.rejects(db.exec("UPDATE purchase_orders SET total=0 WHERE id='po1'"),/draft/);
await assert.rejects(db.exec("INSERT INTO purchase_events VALUES('po-fast','po1','approve','finance','u1','{}')"),/Review is required/);
await db.exec("SELECT set_config('app.user_id','u2',false); INSERT INTO purchase_events VALUES('po-review','po1','review','','u2','{}'); INSERT INTO purchase_events VALUES('po-manager','po1','approve','manager','u2','{}');");
await assert.rejects(db.exec("INSERT INTO purchase_events VALUES('po-self-finance','po1','approve','finance','u2','{}')"),/stage permission|duplicate/);
await db.exec("SELECT set_config('app.user_id','u1',false); INSERT INTO purchase_events VALUES('po-finance','po1','approve','finance','u1','{}');");
assert.equal((await db.query("SELECT sum(total)::bigint n FROM purchase_orders WHERE purchase_approved(id)")).rows[0].n,16500000);
await assert.rejects(db.exec("INSERT INTO stock_lots VALUES('lot-rental','po1','t1','pl2','{}')"),/purchased materials/);
await db.exec("INSERT INTO stock_lots VALUES('lot1','po1','t1','pl1','{}'); INSERT INTO stock_movements VALUES('receipt1','lot1','t1','receipt',2000,NULL,'u1','{}');");
await assert.rejects(db.exec("INSERT INTO stock_movements VALUES('excess-receipt','lot1','t1','receipt',1,NULL,'u1','{}')"),/remaining ordered/);
await assert.rejects(db.exec("INSERT INTO stock_movements VALUES('unpaired','lot1','t2','transfer-in',500,'missing','u1','{}')"),/matching source/);
await db.exec("BEGIN; INSERT INTO stock_movements VALUES('transfer-in','lot1','t2','transfer-in',750,'transfer1','u1','{}'); INSERT INTO stock_movements VALUES('transfer-out','lot1','t1','transfer-out',-750,'transfer1','u1','{}'); COMMIT; INSERT INTO stock_movements VALUES('issue1','lot1','t1','issue',-250,NULL,'u1','{}');");
assert.equal((await db.query("SELECT sum(quantity_milli)::bigint n FROM stock_movements WHERE tenant_id='t1'")).rows[0].n,1000);
assert.equal((await db.query("SELECT sum(quantity_milli)::bigint n FROM stock_movements WHERE tenant_id='t2'")).rows[0].n,750);
assert.equal((await db.query("SELECT coalesce(sum(total),0)::bigint n FROM purchase_orders WHERE tenant_id='t2' AND purchase_approved(id)")).rows[0].n,0);
await assert.rejects(db.exec("INSERT INTO stock_movements VALUES('negative','lot1','t1','issue',-1001,NULL,'u1','{}')"),/available project stock/);
await assert.rejects(db.exec("UPDATE stock_movements SET quantity_milli=1 WHERE id='receipt1'"),/permission denied|immutable/);
await assert.rejects(db.exec("UPDATE tenants SET deleted=true WHERE id='t1'"),/remaining inventory/);
await db.exec("INSERT INTO purchase_orders(id,tenant_id,number,total,vendor_id,form_version,created_by,body) SELECT 'po2','t2','PO-DISTINCT',total,'v6',1,'u1',body || '{\"id\":\"po2\",\"tenantId\":\"t2\"}'::jsonb FROM purchase_orders WHERE id='po1'; INSERT INTO purchase_events VALUES('po2-submit','po2','submit','','u1','{}'),('po2-review','po2','review','','u1','{}'),('po2-manager','po2','approve','manager','u1','{}');");
await assert.rejects(db.exec("INSERT INTO purchase_events VALUES('po2-finance','po2','approve','finance','u1','{}')"),/duplicate/);
await db.exec("UPDATE tenants SET deleted=true WHERE id='t3'; SELECT set_config('app.user_id','u4',false);");
assert.equal((await db.query("SELECT count(*) n FROM stock_movements WHERE tenant_id='t3'")).rows[0].n,0);
await assert.rejects(db.exec("INSERT INTO stock_movements VALUES('engineer-receipt','lot1','t1','receipt',1,NULL,'u4','{}')"),/permission/);
await db.exec("SELECT set_config('app.user_id','u1',false); INSERT INTO stock_movements VALUES('issue-rest','lot1','t1','issue',-1000,NULL,'u1','{}'); UPDATE tenants SET deleted=true WHERE id='t1'; SELECT set_config('app.user_id','u2',false);");
assert.equal((await db.query("SELECT count(*) n FROM tenants WHERE id='t1'")).rows[0].n,0);
assert.equal((await db.query("SELECT count(*) n FROM stock_movements WHERE tenant_id='t1'")).rows[0].n,0);
assert.equal((await db.query("SELECT count(*) n FROM stock_lots WHERE id='lot1'")).rows[0].n,1); // Target project's transferred stock remains accessible.
await db.exec("SELECT set_config('app.user_id','u1',false);");
assert.equal((await db.query("SELECT count(*) n FROM purchase_orders WHERE id='po1'")).rows[0].n,1);
await db.exec("RESET ROLE; GRANT SELECT,INSERT ON work_order_purchase_reference TO ledger_app; GRANT INSERT ON work_orders TO ledger_app; SET ROLE ledger_app; SELECT set_config('app.user_id','u1',false);");
await assert.rejects(db.exec("INSERT INTO work_order_purchase_reference VALUES('w5','t2','po2')"),/approved purchase/);
await assert.rejects(db.exec("INSERT INTO work_order_purchase_reference VALUES('w5','t2','po1')"),/foreign key/);
await db.exec("INSERT INTO work_order_purchase_reference VALUES('w1','t1','po1');");
const itemBody={items:[{description:'Cable installation',unit:'metre',quantityMilli:1250,rate:101,amount:126,startDate:'2026-10-01',endDate:'2026-10-31'}]};
await db.query("INSERT INTO work_orders(id,tenant_id,number,base,form_id,form_version,created_by,body) VALUES('item-order','t2','WO-ITEMS',126,'work_order',1,'u1',$1)",[JSON.stringify(itemBody)]);
await assert.rejects(db.query("INSERT INTO work_orders(id,tenant_id,number,base,form_id,form_version,created_by,body) VALUES('bad-items','t2','WO-BAD',127,'work_order',1,'u1',$1)",[JSON.stringify(itemBody)]),/equal item amounts/);
itemBody.items[0].endDate='2026-09-01';await assert.rejects(db.query("INSERT INTO work_orders(id,tenant_id,number,base,form_id,form_version,created_by,body) VALUES('bad-period','t2','WO-DATE',126,'work_order',1,'u1',$1)",[JSON.stringify(itemBody)]),/Period end/);
const linkedBody={...itemBody,items:[{...itemBody.items[0],endDate:'2026-10-31'}],purchaseOrderId:'po1',purchaseOrderNumber:'PO-SKY-001',purchaseOrderDate:'2026-10-05'};
await db.exec('BEGIN;');await db.query("INSERT INTO work_orders(id,tenant_id,number,base,form_id,form_version,created_by,body) VALUES('linked-item','t1','WO-LINKED',126,'work_order',1,'u1',$1)",[JSON.stringify(linkedBody)]);await db.exec("INSERT INTO work_order_purchase_reference VALUES('linked-item','t1','po1');COMMIT;");
await assert.rejects(db.query("INSERT INTO work_orders(id,tenant_id,number,base,form_id,form_version,created_by,body) VALUES('missing-ref','t1','WO-MISSING-REF',126,'work_order',1,'u1',$1)",[JSON.stringify(linkedBody)]),/reference is missing/);
assert.equal((await db.query("SELECT order_date::text AS order_date FROM purchase_orders WHERE id='po2'")).rows[0].order_date,'2026-10-05');
await db.exec("RESET ROLE; GRANT DELETE ON roles,membership_roles TO ledger_app; SET ROLE ledger_app; SELECT set_config('app.user_id','u4',false);");
assert.equal((await db.query("DELETE FROM roles WHERE id='manager' RETURNING id")).rows.length,0);
assert.equal((await db.query("DELETE FROM membership_roles WHERE role_id='manager' RETURNING user_id")).rows.length,0);
await db.exec("SELECT set_config('app.user_id','u1',false);");
await assert.rejects(db.exec("DELETE FROM roles WHERE id='manager'"),/foreign key/);
await db.exec("BEGIN; DELETE FROM membership_roles WHERE role_id='manager'; DELETE FROM roles WHERE id='manager'; COMMIT;");
assert.equal((await db.query("SELECT count(*) n FROM membership_roles WHERE role_id='manager'")).rows[0].n,0);
assert.equal((await db.query("SELECT count(*) n FROM roles WHERE id='manager'")).rows[0].n,0);
assert.equal((await db.query("SELECT count(*) n FROM membership_roles WHERE role_id='engineer'")).rows[0].n,2);
assert.equal((await db.query("SELECT count(*) n FROM purchase_events WHERE purchase_order_id='po1' AND action='approve'")).rows[0].n,2);
console.log('PASS: migrations, seed, immutable financial history, global RERA uniqueness, approval order, distinct approvers, tenant RLS and effective totals.');
await db.exec('RESET ROLE; BEGIN;'+readFileSync(root+'migrations/007_superuser_approval_policy.sql','utf8')+'COMMIT;');
assert.equal((await db.query("SELECT effective_total('w1') total")).rows[0].total,140000000);
assert.equal((await db.query("SELECT purchase_approved('po1') approved")).rows[0].approved,true);
assert.equal((await db.query("SELECT approval_policy FROM purchase_orders WHERE id='po1'")).rows[0].approval_policy,1);
await db.close();

});
