SELECT set_config('app.user_id','u1',true);
INSERT INTO users VALUES('u1','Rohith Krishna','Platform superuser',true,crypt('BuildLedger-demo-2026!',gen_salt('bf')));
INSERT INTO users VALUES('u2','Ananya Rao','Project manager',false,crypt('BuildLedger-demo-2026!',gen_salt('bf')));
INSERT INTO users VALUES('u3','Kiran Shah','Finance approver',false,crypt('BuildLedger-demo-2026!',gen_salt('bf')));
INSERT INTO users VALUES('u4','Ravi Kumar','Site engineer',false,crypt('BuildLedger-demo-2026!',gen_salt('bf')));
INSERT INTO tenants VALUES('t1','SKY','{"id":"t1","name":"Skyline Residences","code":"SKY","location":"Hyderabad, Telangana"}'::jsonb);
INSERT INTO tenants VALUES('t2','NGP','{"id":"t2","name":"Northgate Business Park","code":"NGP","location":"Bengaluru, Karnataka"}'::jsonb);
INSERT INTO tenants VALUES('t3','LKV','{"id":"t3","name":"Lakeview Villas","code":"LKV","location":"Hyderabad, Telangana"}'::jsonb);
INSERT INTO roles VALUES('manager','{"id":"manager","name":"Project Manager","stage":"manager","permissions":{"work_order":{"actions":["view","create","edit","submit","review","approve","reject","amend"],"fields":{"amount":"view","description":"edit","reason":"edit","contract_package":"edit","retention":"edit"}},"rera_account":{"actions":["view"],"fields":{"number":"view","bank":"view","ifsc":"view","label":"view"}}}}'::jsonb);
INSERT INTO roles VALUES('finance','{"id":"finance","name":"Finance Approver","stage":"finance","permissions":{"work_order":{"actions":["view","create","edit","submit","review","approve","reject","amend"],"fields":{"amount":"edit","description":"view","reason":"edit","contract_package":"edit","retention":"edit"}},"rera_account":{"actions":["view"],"fields":{"number":"view","bank":"view","ifsc":"view","label":"view"}}}}'::jsonb);
INSERT INTO roles VALUES('engineer','{"id":"engineer","name":"Site Engineer","stage":"","permissions":{"work_order":{"actions":["view"],"fields":{"amount":"hidden","description":"view","reason":"view","contract_package":"view","retention":"hidden"}},"rera_account":{"actions":[],"fields":{"number":"hidden","bank":"hidden","ifsc":"hidden","label":"hidden"}}}}'::jsonb);
INSERT INTO memberships VALUES('t1','u2');
INSERT INTO membership_roles VALUES('t1','u2','manager');
INSERT INTO memberships VALUES('t1','u3');
INSERT INTO membership_roles VALUES('t1','u3','finance');
INSERT INTO memberships VALUES('t1','u4');
INSERT INTO membership_roles VALUES('t1','u4','engineer');
INSERT INTO memberships VALUES('t2','u2');
INSERT INTO membership_roles VALUES('t2','u2','manager');
INSERT INTO memberships VALUES('t2','u3');
INSERT INTO membership_roles VALUES('t2','u3','finance');
INSERT INTO memberships VALUES('t2','u4');
INSERT INTO membership_roles VALUES('t2','u4','engineer');
INSERT INTO membership_roles VALUES('t2','u4','manager');
INSERT INTO form_versions VALUES('work_order',1,'{"id":"work_order","name":"Work Order","version":1,"fields":[{"key":"contract_package","label":"Contract package","type":"text","required":true},{"key":"retention","label":"Retention (%)","type":"number","required":false}],"createdAt":"2026-09-01T08:00:00Z","createdBy":"u1"}'::jsonb);
INSERT INTO form_versions VALUES('rera_account',1,'{"id":"rera_account","name":"RERA Bank Account","version":1,"fields":[],"createdBy":"u1","createdAt":"2026-09-01T08:00:00Z"}'::jsonb);
INSERT INTO rera_accounts VALUES('r1','t1','501008742631','{"id":"r1","tenantId":"t1","number":"501008742631","bank":"HDFC Bank","ifsc":"HDFC0000214","label":"Project receipts · Phase I"}'::jsonb);
INSERT INTO rera_accounts VALUES('r2','t1','501008742649','{"id":"r2","tenantId":"t1","number":"501008742649","bank":"HDFC Bank","ifsc":"HDFC0000214","label":"Project expenses · Phase II"}'::jsonb);
INSERT INTO rera_accounts VALUES('r3','t2','019405000672','{"id":"r3","tenantId":"t2","number":"019405000672","bank":"ICICI Bank","ifsc":"ICIC0000194","label":"Project receipts · Main block"}'::jsonb);
INSERT INTO work_orders VALUES('w1','t1','WO-SKY-001',120000000,'work_order',1,'u1','{"id":"w1","tenantId":"t1","number":"WO-SKY-001","vendor":"Sri Sai Constructions","description":"Civil & structural works · Tower A","base":120000000,"formId":"work_order","formVersion":1,"data":{"contract_package":"Civil works","retention":"5"},"createdBy":"u1","createdAt":"2026-09-12T09:00:00Z"}'::jsonb);
INSERT INTO work_orders VALUES('w2','t1','WO-SKY-002',48500000,'work_order',1,'u1','{"id":"w2","tenantId":"t1","number":"WO-SKY-002","vendor":"Vertex Electricals","description":"Electrical installation · Phase I","base":48500000,"formId":"work_order","formVersion":1,"data":{"contract_package":"Electrical","retention":"5"},"createdBy":"u1","createdAt":"2026-09-16T09:00:00Z"}'::jsonb);
INSERT INTO work_orders VALUES('w3','t1','WO-SKY-003',32000000,'work_order',1,'u1','{"id":"w3","tenantId":"t1","number":"WO-SKY-003","vendor":"AquaFlow Systems","description":"Plumbing & fire safety","base":32000000,"formId":"work_order","formVersion":1,"data":{"contract_package":"MEP","retention":"3"},"createdBy":"u1","createdAt":"2026-09-22T09:00:00Z"}'::jsonb);
INSERT INTO work_orders VALUES('w4','t1','WO-SKY-004',21000000,'work_order',1,'u1','{"id":"w4","tenantId":"t1","number":"WO-SKY-004","vendor":"Stonecraft Interiors","description":"Flooring & finishes · Tower B","base":21000000,"formId":"work_order","formVersion":1,"data":{"contract_package":"Interiors","retention":"5"},"createdBy":"u1","createdAt":"2026-09-25T09:00:00Z"}'::jsonb);
INSERT INTO work_orders VALUES('w5','t2','WO-NGP-001',248000000,'work_order',1,'u1','{"id":"w5","tenantId":"t2","number":"WO-NGP-001","vendor":"Metro Build Contractors","description":"Commercial structure · Main block","base":248000000,"formId":"work_order","formVersion":1,"data":{"contract_package":"Civil works","retention":"5"},"createdBy":"u1","createdAt":"2026-09-19T09:00:00Z"}'::jsonb);
INSERT INTO amendments VALUES('a1','w1',20000000,'u1',NULL,'{"id":"a1","orderId":"w1","delta":20000000,"reason":"Additional foundation works following soil report","data":{"contract_package":"Civil works","retention":"5"},"formVersion":1,"createdBy":"u1","createdAt":"2026-09-26T09:00:00Z"}'::jsonb);
INSERT INTO amendments VALUES('a2','w2',6500000,'u1',NULL,'{"id":"a2","orderId":"w2","delta":6500000,"reason":"Revised cable routing and additional distribution boards","data":{"contract_package":"Electrical","retention":"5"},"formVersion":1,"createdBy":"u1","createdAt":"2026-10-03T09:00:00Z"}'::jsonb);
INSERT INTO amendments VALUES('a3','w3',-2000000,'u1',NULL,'{"id":"a3","orderId":"w3","delta":-2000000,"reason":"Scope reduction: external drainage package reassigned","data":{"contract_package":"MEP","retention":"3"},"formVersion":1,"createdBy":"u1","createdAt":"2026-10-04T09:00:00Z"}'::jsonb);
INSERT INTO amendment_events VALUES('e1','a1','submit','','u1','{"id":"e1","amendmentId":"a1","action":"submit","actorId":"u1","at":"2026-09-26T10:00:00Z"}'::jsonb);
INSERT INTO amendment_events VALUES('e2','a1','review','','u2','{"id":"e2","amendmentId":"a1","action":"review","actorId":"u2","at":"2026-09-26T11:00:00Z"}'::jsonb);
INSERT INTO amendment_events VALUES('e3','a1','approve','manager','u2','{"id":"e3","amendmentId":"a1","action":"approve","stage":"manager","actorId":"u2","at":"2026-09-27T09:00:00Z"}'::jsonb);
INSERT INTO amendment_events VALUES('e4','a1','approve','finance','u3','{"id":"e4","amendmentId":"a1","action":"approve","stage":"finance","actorId":"u3","at":"2026-09-27T10:00:00Z"}'::jsonb);
INSERT INTO amendment_events VALUES('e5','a2','submit','','u1','{"id":"e5","amendmentId":"a2","action":"submit","actorId":"u1","at":"2026-10-03T10:00:00Z"}'::jsonb);
INSERT INTO amendment_events VALUES('e6','a2','review','','u2','{"id":"e6","amendmentId":"a2","action":"review","actorId":"u2","at":"2026-10-03T11:00:00Z"}'::jsonb);
INSERT INTO amendment_events VALUES('e7','a2','approve','manager','u2','{"id":"e7","amendmentId":"a2","action":"approve","stage":"manager","actorId":"u2","at":"2026-10-03T12:00:00Z"}'::jsonb);
INSERT INTO amendment_events VALUES('e8','a3','submit','','u1','{"id":"e8","amendmentId":"a3","action":"submit","actorId":"u1","at":"2026-10-04T10:00:00Z"}'::jsonb);
INSERT INTO audit_log VALUES('l1','t1','u3','{"id":"l1","tenantId":"t1","actorId":"u3","action":"Finance approval recorded","target":"WO-SKY-001","at":"2026-09-27T10:00:00Z"}'::jsonb);
INSERT INTO audit_log VALUES('l2','t1','u2','{"id":"l2","tenantId":"t1","actorId":"u2","action":"Manager approval recorded","target":"WO-SKY-002","at":"2026-10-03T12:00:00Z"}'::jsonb);
INSERT INTO audit_log VALUES('l3','t1','u1','{"id":"l3","tenantId":"t1","actorId":"u1","action":"Amendment submitted","target":"WO-SKY-003","at":"2026-10-04T10:00:00Z"}'::jsonb);
