import {seedPayments} from './payment-schedules.js';
import {seedSuite} from './suite-seed.js';
export const money=n=> n==null?'Restricted':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n/100);
export const stamp=()=>new Date().toISOString();
export const uid=()=>crypto.randomUUID();
export const actions=['view','create','edit','submit','review','approve','reject','amend'];
export const fieldKeys=['amount','description','reason'];
export const normalizeRera=s=>s.trim().toUpperCase().replace(/\s+/g,'');
export function seed(){const s={
users:[{id:'u1',name:'Rohith Krishna',title:'Platform superuser',superuser:true},{id:'u2',name:'Ananya Rao',title:'Project manager'},{id:'u3',name:'Kiran Shah',title:'Finance approver'},{id:'u4',name:'Ravi Kumar',title:'Site engineer'}],
tenants:[{id:'t1',name:'Skyline Residences',code:'SKY',location:'Hyderabad, Telangana'},{id:'t2',name:'Northgate Business Park',code:'NGP',location:'Bengaluru, Karnataka'},{id:'t3',name:'Lakeview Villas',code:'LKV',location:'Hyderabad, Telangana'}],
reras:[{id:'r1',tenantId:'t1',number:'501008742631',bank:'HDFC Bank',ifsc:'HDFC0000214',label:'Project receipts · Phase I'},{id:'r2',tenantId:'t1',number:'501008742649',bank:'HDFC Bank',ifsc:'HDFC0000214',label:'Project expenses · Phase II'},{id:'r3',tenantId:'t2',number:'019405000672',bank:'ICICI Bank',ifsc:'ICIC0000194',label:'Project receipts · Main block'}],
roles:[{id:'manager',name:'Project Manager',stage:'manager',permissions:{work_order:{actions:['view','create','edit','submit','review','approve','reject','amend'],fields:{amount:'view',description:'edit',reason:'edit',contract_package:'edit',retention:'edit'}}}},{id:'finance',name:'Finance Approver',stage:'finance',permissions:{work_order:{actions:['view','create','edit','submit','review','approve','reject','amend'],fields:{amount:'edit',description:'view',reason:'edit',contract_package:'edit',retention:'edit'}}}},{id:'engineer',name:'Site Engineer',stage:'',permissions:{work_order:{actions:['view'],fields:{amount:'hidden',description:'view',reason:'view',contract_package:'view',retention:'hidden'}}}}],
memberships:[{tenantId:'t1',userId:'u2',roleIds:['manager']},{tenantId:'t1',userId:'u3',roleIds:['finance']},{tenantId:'t1',userId:'u4',roleIds:['engineer']},{tenantId:'t2',userId:'u2',roleIds:['manager']},{tenantId:'t2',userId:'u3',roleIds:['finance']},{tenantId:'t2',userId:'u4',roleIds:['engineer','manager']}],
forms:[{id:'work_order',name:'Work Order',version:1,fields:[{key:'contract_package',label:'Contract package',type:'text',required:true},{key:'retention',label:'Retention (%)',type:'number',required:false}],createdAt:'2026-09-01T08:00:00Z',createdBy:'u1'}],
orders:[{id:'w1',tenantId:'t1',number:'WO-SKY-001',vendor:'Sri Sai Constructions',description:'Civil & structural works · Tower A',base:120000000,formId:'work_order',formVersion:1,data:{contract_package:'Civil works',retention:'5'},createdBy:'u1',createdAt:'2026-09-12T09:00:00Z'},{id:'w2',tenantId:'t1',number:'WO-SKY-002',vendor:'Vertex Electricals',description:'Electrical installation · Phase I',base:48500000,formId:'work_order',formVersion:1,data:{contract_package:'Electrical',retention:'5'},createdBy:'u1',createdAt:'2026-09-16T09:00:00Z'},{id:'w3',tenantId:'t1',number:'WO-SKY-003',vendor:'AquaFlow Systems',description:'Plumbing & fire safety',base:32000000,formId:'work_order',formVersion:1,data:{contract_package:'MEP',retention:'3'},createdBy:'u1',createdAt:'2026-09-22T09:00:00Z'},{id:'w4',tenantId:'t1',number:'WO-SKY-004',vendor:'Stonecraft Interiors',description:'Flooring & finishes · Tower B',base:21000000,formId:'work_order',formVersion:1,data:{contract_package:'Interiors',retention:'5'},createdBy:'u1',createdAt:'2026-09-25T09:00:00Z'},{id:'w5',tenantId:'t2',number:'WO-NGP-001',vendor:'Metro Build Contractors',description:'Commercial structure · Main block',base:248000000,formId:'work_order',formVersion:1,data:{contract_package:'Civil works',retention:'5'},createdBy:'u1',createdAt:'2026-09-19T09:00:00Z'}],
amendments:[{id:'a1',orderId:'w1',delta:20000000,reason:'Additional foundation works following soil report',data:{contract_package:'Civil works',retention:'5'},formVersion:1,createdBy:'u1',createdAt:'2026-09-26T09:00:00Z'},{id:'a2',orderId:'w2',delta:6500000,reason:'Revised cable routing and additional distribution boards',data:{contract_package:'Electrical',retention:'5'},formVersion:1,createdBy:'u1',createdAt:'2026-10-03T09:00:00Z'},{id:'a3',orderId:'w3',delta:-2000000,reason:'Scope reduction: external drainage package reassigned',data:{contract_package:'MEP',retention:'3'},formVersion:1,createdBy:'u1',createdAt:'2026-10-04T09:00:00Z'}],
events:[{id:'e1',amendmentId:'a1',action:'submit',actorId:'u1',at:'2026-09-26T10:00:00Z'},{id:'e2',amendmentId:'a1',action:'review',actorId:'u2',at:'2026-09-26T11:00:00Z'},{id:'e3',amendmentId:'a1',action:'approve',stage:'manager',actorId:'u2',at:'2026-09-27T09:00:00Z'},{id:'e4',amendmentId:'a1',action:'approve',stage:'finance',actorId:'u3',at:'2026-09-27T10:00:00Z'},{id:'e5',amendmentId:'a2',action:'submit',actorId:'u1',at:'2026-10-03T10:00:00Z'},{id:'e6',amendmentId:'a2',action:'review',actorId:'u2',at:'2026-10-03T11:00:00Z'},{id:'e7',amendmentId:'a2',action:'approve',stage:'manager',actorId:'u2',at:'2026-10-03T12:00:00Z'},{id:'e8',amendmentId:'a3',action:'submit',actorId:'u1',at:'2026-10-04T10:00:00Z'}],audit:[{id:'l1',tenantId:'t1',actorId:'u3',action:'Finance approval recorded',target:'WO-SKY-001',at:'2026-09-27T10:00:00Z'},{id:'l2',tenantId:'t1',actorId:'u2',action:'Manager approval recorded',target:'WO-SKY-002',at:'2026-10-03T12:00:00Z'},{id:'l3',tenantId:'t1',actorId:'u1',action:'Amendment submitted',target:'WO-SKY-003',at:'2026-10-04T10:00:00Z'}],uploads:[]};
for(const r of s.roles){r.permissions.rera_account={actions:r.id==='engineer'?[]:['view'],fields:{number:r.id==='engineer'?'hidden':'view',bank:r.id==='engineer'?'hidden':'view',ifsc:r.id==='engineer'?'hidden':'view',label:r.id==='engineer'?'hidden':'view'}};}
s.vendors=s.orders.map((o,i)=>({id:'v'+(i+1),tenantId:o.tenantId,name:o.vendor,trade:o.data.contract_package,contactName:['Srinivas Reddy','Deepak Nair','Meera Patel','Arjun Mehta','Vikram Rao'][i],phone:'90000000'+String(i+10),email:'vendor'+(i+1)+'@example.com',gstin:'',address:o.tenantId==='t1'?'Hyderabad, Telangana':'Bengaluru, Karnataka',deleted:false}));
s.vendors.push({id:'v6',tenantId:'t2',name:'Sri Sai Constructions',trade:'Civil works',contactName:'Srinivas Reddy',phone:'9000000010',email:'vendor1@example.com',gstin:'',address:'Bengaluru project office',deleted:false});
for(const o of s.orders){const v=s.vendors.find(v=>v.tenantId===o.tenantId&&v.name===o.vendor);o.vendorId=v.id;o.vendorSnapshot={...v};}
for(const u of s.users)u.username=u.id;
for(const r of s.roles){r.permissions.vendor={actions:['view'],fields:{name:'view',trade:'view',contactName:'view',phone:'view',email:'view',gstin:r.id==='engineer'?'hidden':'view',address:'view'}};}
s.forms.push({id:'vendor',name:'Vendor Details',version:1,fields:[],createdBy:'u1',createdAt:'2026-09-01T08:00:00Z'});
s.forms.push({id:'rera_account',name:'RERA Bank Account',version:1,fields:[],createdBy:'u1',createdAt:'2026-09-01T08:00:00Z'});for(const r of s.roles){for(const k of ['unit','period','quantity','purchase_reference'])r.permissions.work_order.fields[k]=r.id==='engineer'?'view':'edit';r.permissions.purchase_order={actions:r.id==='engineer'?['view']:['view','create','edit','submit','review','approve','reject'],fields:{amount:r.id==='engineer'?'hidden':'edit',description:r.id==='engineer'?'view':'edit',materials:r.id==='engineer'?'view':'edit'}};r.permissions.inventory={actions:r.id==='engineer'?['view']:['view','create','edit'],fields:{materials:r.id==='engineer'?'view':'edit',quantity:r.id==='engineer'?'view':'edit'}};}
for(const r of s.roles)r.permissions.purchase_order.fields.order_date=r.id==='engineer'?'view':'edit';
s.forms.push({id:'purchase_order',name:'Purchase Order',version:1,fields:[],createdBy:'u1',createdAt:'2026-10-05T08:00:00Z'},{id:'inventory',name:'Inventory',version:1,fields:[],createdBy:'u1',createdAt:'2026-10-05T08:00:00Z'});
s.purchaseOrders=[{id:'po1',tenantId:'t1',number:'PO-SKY-001',description:'Tower A slab materials and equipment hire',vendorId:'v1',vendor:'Sri Sai Constructions',vendorSnapshot:{...s.vendors[0]},lines:[{id:'pl1',kind:'purchase',material:'TMT steel · Fe500',unit:'tonne',quantityMilli:2000,rate:6500000,total:13000000},{id:'pl2',kind:'rental',material:'Concrete mixer hire',unit:'day',quantityMilli:10000,rate:350000,total:3500000}],total:16500000,formVersion:1,data:{},createdBy:'u1',createdAt:'2026-10-05T08:00:00Z'}];s.purchaseOrders[0].orderDate='2026-10-05';s.purchaseEvents=[];s.stockLots=[];s.stockMovements=[];for(const a of s.amendments){a.approvalPolicy=a.id==='a1'?1:2;a.creatorSuperuser=true;}
s.purchaseOrders[0].approvalPolicy=2;s.purchaseOrders[0].creatorSuperuser=true;
const adminRole=structuredClone(s.roles.find(r=>r.id==='manager'));adminRole.permissions.work_order.fields.amount='edit';adminRole.id='admin';adminRole.name='Admin';adminRole.stage='admin';s.roles.push(adminRole);

for(const v of s.vendors){v.onboardingStatus='Active';v.vendorType='Subcontractor';v.pan='';v.notes='';}
const fFields=['amount','description','category','dates','remarks','reference'];
for(const id of ['expense','payment','cost_overview','vendor_onboarding'])s.forms.push({id,name:{expense:'Construction Expense',payment:'Vendor Payment',cost_overview:'Project Cost Overview',vendor_onboarding:'Vendor Onboarding'}[id],version:1,fields:[]});
for(const r of s.roles){if(['manager','admin','finance'].includes(r.stage)){for(const id of ['expense','payment'])r.permissions[id]={actions:['view','create','edit','submit','review','approve','reject',...(id==='payment'?['amend']:[])],fields:Object.fromEntries(fFields.map(k=>[k,'edit']))};}if(r.stage==='admin'){r.permissions.cost_overview={actions:['view'],fields:{amount:'view'}};r.permissions.vendor_onboarding={actions:['view','create','edit','submit'],fields:Object.fromEntries(vendorFields.map(k=>[k,'edit']))};}}
s.expenses=[{id:'ex1',kind:'expense',tenantId:'t1',description:'Structural design consultancy · September',category:'Consultant charges',payee:'Aster Structural Consultants',expenseDate:'2026-10-01',amount:6400000,remarks:'Monthly retainer',referenceType:'',referenceId:'',formVersion:1,data:{},createdBy:'u1',createdAt:'2026-10-01T10:00:00Z',approvalPolicy:2,creatorSuperuser:true},{id:'ex2',kind:'expense',tenantId:'t1',description:'Site office salaries · September',category:'Salaries',payee:'Site payroll',expenseDate:'2026-10-02',amount:4800000,remarks:'Awaiting superuser approval',referenceType:'',referenceId:'',formVersion:1,data:{},createdBy:'u2',createdAt:'2026-10-02T10:00:00Z',approvalPolicy:2,creatorSuperuser:false},{id:'ex3',kind:'expense',tenantId:'t1',description:'Site office administration',category:'Admin costs',payee:'Site office',expenseDate:'2026-10-04',amount:1200000,remarks:'',referenceType:'',referenceId:'',formVersion:1,data:{},createdBy:'u1',createdAt:'2026-10-04T10:00:00Z',approvalPolicy:2,creatorSuperuser:true}];
s.invoices=[{id:'inv1',tenantId:'t1',orderId:'w1',orderNumber:s.orders[0].number,orderDate:s.orders[0].createdAt.slice(0,10),vendorId:'v1',vendor:s.vendors[0].name,invoiceNumber:'SSC-2026-041',invoiceDate:'2026-10-01',amount:10000000,description:'Tower A civil works · first running bill',category:'Civil works',remarks:'Partial settlement',createdBy:'u1',createdAt:'2026-10-01T11:00:00Z'}];
s.payments=[{id:'pay1',kind:'payment',tenantId:'t1',invoiceId:'inv1',paid:4500000,tds:500000,amount:5000000,paidDate:'2026-10-04',remarks:'First partial payment',formVersion:1,data:{},createdBy:'u1',createdAt:'2026-10-04T11:00:00Z',approvalPolicy:2,creatorSuperuser:true}];
s.financeEvents=[{id:'fe1',documentId:'ex1',action:'submit',actorId:'u1',stage:'',at:'2026-10-01T12:00:00Z'},{id:'fe2',documentId:'ex1',action:'approve',actorId:'u1',stage:'superuser',at:'2026-10-01T12:10:00Z'},{id:'fe3',documentId:'ex2',action:'submit',actorId:'u2',stage:'',at:'2026-10-02T12:00:00Z'},{id:'fe4',documentId:'ex2',action:'review',actorId:'u3',stage:'',at:'2026-10-02T12:10:00Z'},{id:'fe5',documentId:'ex2',action:'approve',actorId:'u3',stage:'finance',at:'2026-10-02T12:20:00Z'}];s.invoiceEvents=[];
s.vendors.push({id:'v7',tenantId:'t1',name:'Aster Structural Consultants',trade:'Structural consultancy',vendorType:'Consultant',contactName:'Neha Menon',phone:'9876543210',email:'neha@example.com',address:'Hyderabad',gstin:'',pan:'',notes:'Design consultancy for Tower A',onboardingStatus:'Submitted',createdBy:'u1',createdAt:'2026-10-04T10:00:00Z',deleted:false});
seedSuite(s);seedPayments(s);return s;}
export function status(state,a){
  const events=state.events.filter(e=>e.amendmentId===a.id);
  if(events.some(e=>e.action==='reject'))return 'Rejected';
  const approvals=events.filter(e=>e.action==='approve');
  if(a.approvalPolicy!==2){
    if(approvals.some(e=>e.stage==='finance'))return 'Approved';
    if(approvals.some(e=>e.stage==='manager'))return 'Finance approval';
    if(events.some(e=>e.action==='review'))return 'Manager approval';
    return events.some(e=>e.action==='submit')?'Review':'Draft';
  }
  const su=approvals.find(e=>e.stage==='superuser');
  const partner=approvals.find(e=>['admin','finance'].includes(e.stage));
  if(su&&(a.creatorSuperuser||(partner&&su.actorId!==partner.actorId)))return 'Approved';
  if(!events.some(e=>e.action==='submit'))return 'Draft';
  if(a.creatorSuperuser)return 'Superuser approval';
  if(!events.some(e=>e.action==='review'))return 'Review';
  if(su)return 'Admin / Finance approval';
  if(partner)return 'Superuser approval';
  return 'Admin / Finance + Superuser';
}
export const approvalStageLabel=stage=>({superuser:'Superuser approval',admin:'Admin approval',finance:'Finance approval',manager:'Manager approval (previous policy)'}[stage]||stage);
export const approvalRequirement=a=>a.approvalPolicy!==2?'Previous policy · Manager + Finance':a.creatorSuperuser?'Superuser direct approval · no finance approval required':'Two approvals · Admin + Superuser or Superuser + Finance';
export function approvalStage(s,u,t,a,events,form='work_order'){
  const st=status({events},a);
  if(!can(s,u,t,'approve',form)||(a.createdBy===u.id&&!u.superuser)||['Draft','Approved','Rejected'].includes(st))return '';
  const ev=events.filter(e=>e.amendmentId===a.id);
  if(ev.some(e=>e.action==='approve'&&e.actorId===u.id&&(a.approvalPolicy!==2||e.stage!=='manager')))return '';
  if(a.approvalPolicy!==2){const stage=st==='Manager approval'?'manager':st==='Finance approval'?'finance':'';return stage&&stageFor(s,u,t)[stage]?stage:'';}
  if(a.creatorSuperuser)return u.superuser?'superuser':'';
  if(!ev.some(e=>e.action==='review'))return '';
  if(u.superuser)return ev.some(e=>e.action==='approve'&&e.stage==='superuser')?'':'superuser';
  if(ev.some(e=>e.action==='approve'&&['admin','finance'].includes(e.stage)))return '';
  // Approval stage and form action must be granted by the same assigned role.
  return roleList(s,u,t).find(r=>['admin','finance'].includes(r.stage)&&r.permissions[form]?.actions?.includes('approve'))?.stage||'';
}
export const effective=(s,o)=>o.base==null?null:o.workflowEnabled&&status({events:(s.orderEvents||[]).map(e=>({...e,amendmentId:e.orderId}))},o)!=='Approved'?0:o.base+s.amendments.filter(a=>a.orderId===o.id&&status(s,a)==='Approved').reduce((n,a)=>n+(a.delta??0),0);
export function roleList(s,u,t){return s.roles.filter(r=>s.memberships.some(m=>m.userId===u.id&&m.tenantId===t&&m.roleIds.includes(r.id)));}
export function can(s,u,t,action,form='work_order'){return !!u.superuser||roleList(s,u,t).some(r=>r.permissions[form]?.actions?.includes(action));}
export function fieldAccess(s,u,t,key,form='work_order'){if(u.superuser)return 'edit';const modes=roleList(s,u,t).map(r=>r.permissions[form]?.fields?.[key]??'hidden');return modes.includes('edit')?'edit':modes.includes('view')?'view':'hidden';}
export function stageFor(s,u,t){const r=roleList(s,u,t);return {manager:!!u.superuser||r.some(r=>r.stage==='manager'),admin:r.some(r=>r.stage==='admin'),finance:r.some(r=>r.stage==='finance'),superuser:!!u.superuser};}
export function parseCSV(text){if(text.length>1000000)throw Error('CSV must be smaller than 1 MB.');const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(!quoted&&cell.length)throw Error('Unexpected quote in CSV.');else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Unclosed quoted field.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);if(rows.length<2)throw Error('CSV must contain a header and at least one row.');return rows;}
export function cents(v){if(!/^[+-]?\d+(\.\d{1,2})?$/.test(String(v).trim()))throw Error('Use a number with at most two decimal places, without commas or ₹.');const n=Math.round(Number(v)*100);if(!Number.isSafeInteger(n)||Math.abs(n)>1e14)throw Error('Amount is outside the supported range.');return n;}
export function validateCSV(s,u,t,text){if(!can(s,u,t,'amend')||fieldAccess(s,u,t,'amount')!=='edit')throw Error('Your roles do not allow financial imports.');const rows=parseCSV(text),head=rows.shift().map(x=>x.trim().replace(/^\uFEFF/,''));const expected=['work_order','delta_including_tax','reason'];if(head.join(',')!==expected.join(','))throw Error('Expected columns: '+expected.join(', '));if(rows.length>500)throw Error('Maximum 500 rows per upload.');const totals={},errors=[],parsed=[];rows.forEach((r,i)=>{try{if(r.length!==3)throw Error('Expected three columns.');const o=s.orders.find(o=>o.tenantId===t&&o.number===r[0].trim());if(!o)throw Error('Work order does not exist in this project.');if(o.workflowEnabled&&status({events:(s.orderEvents||[]).map(e=>({...e,amendmentId:e.orderId}))},o)!=='Approved')throw Error('Only approved work orders can be amended.');const delta=cents(r[1]);if(!delta)throw Error('Amendment cannot be zero.');if(!r[2].trim())throw Error('Reason is required.');const previous=totals[o.id]??effective(s,o),next=previous+delta;if(next>1e14)throw Error('Resulting total exceeds the supported range.');if(next<0)throw Error(`Resulting total ${money(next)} would be below zero.`);totals[o.id]=next;parsed.push({orderId:o.id,number:o.number,delta,reason:r[2].trim(),previous,next});}catch(e){errors.push({row:i+2,message:e.message});}});return {rows:parsed,errors};}
export function transition(s,u,t,id,action){const a=s.amendments.find(a=>a.id===id),o=s.orders.find(o=>o.id===a?.orderId);if(!a||o?.tenantId!==t)throw Error('Amendment not found.');if(!can(s,u,t,action,o.formId))throw Error('Your roles do not allow this action.');const st=status(s,a),ev=s.events.filter(e=>e.amendmentId===id);let stage='';if(action==='submit'){if(st!=='Draft')throw Error('Only drafts can be submitted.');if(a.createdBy!==u.id&&!u.superuser)throw Error('Only the creator can submit this amendment.');}else{if(a.createdBy===u.id&&!u.superuser)throw Error('The creator cannot review, approve or reject their own amendment.');if(action==='review'){if(st!=='Review')throw Error('This amendment is not awaiting review.');}else if(action==='approve'){stage=approvalStage(s,u,t,a,s.events,o.formId||'work_order');if(!stage)throw Error('Approval requires the eligible Admin, Finance or Superuser role; review and two different approvers are required for regular submissions.');if(effective(s,o)+a.delta<0)throw Error('Approval blocked: the resulting total would be below zero.');}else if(action==='reject'){if(['Approved','Rejected','Draft'].includes(st))throw Error('Only pending submissions can be rejected.');}else throw Error('Unsupported action.');}const e={id:uid(),amendmentId:id,action,stage,actorId:u.id,at:stamp(),superuserApproval:!!u.superuser&&action==='approve'};s.events.push(e);s.audit.push({id:uid(),tenantId:t,actorId:u.id,action:action==='approve'?`${approvalStageLabel(stage)} recorded`:`Amendment ${action==='review'?'reviewed':action==='submit'?'submitted':'rejected'}`,target:o.number,at:e.at});return e;}

export const vendorFields=['name','trade','contactName','phone','email','gstin','address','vendorType','pan','onboardingStatus','notes'];
export function canApprove(s,u,t,a){return !!approvalStage(s,u,t,a,s.events);}
export function generatePassword(){const bytes=crypto.getRandomValues(new Uint8Array(24));return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');}
export function vendorDetails(s,u,t,o){if(!can(s,u,t,'view','vendor'))return null;const current=s.vendors?.find(v=>v.id===o?.vendorId&&!v.deleted);const source=current??o?.vendorSnapshot;if(!source)return null;return {...Object.fromEntries(vendorFields.filter(k=>fieldAccess(s,u,t,k,'vendor')!=='hidden').map(k=>[k,source[k]])),...Object.fromEntries(Object.entries(source.vendorData||{}).filter(([k])=>fieldAccess(s,u,t,k,'vendor')!=='hidden'))};}
