import {can,fieldAccess,roleList,uid,stamp,status,transition,effective,approvalStage} from './domain.js';
import {purchaseCost} from './procurement.js';
export const expenseCategories=['Consultant charges','Salaries','Material purchase','Admin costs','Labour','Equipment rental','Transport','Utilities','Site overheads','Insurance','Other'];
export const financeFields=['amount','description','category','dates','remarks','reference'];
export const vendorTrades=['Civil works','Electrical','Plumbing / MEP','Interiors','Material supplier','Consultancy','Equipment rental','Labour contractor','Other'];
export const vendorTypes=['Supplier','Subcontractor','Consultant','Service provider','Other'];
export const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||'')&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
export const financeStatus=(s,d)=>status({events:(s.financeEvents||[]).map(e=>({...e,amendmentId:e.documentId}))},d);
export const settled=(s,id)=>(s.payments||[]).filter(p=>p.invoiceId===id&&financeStatus(s,p)==='Approved').reduce((n,p)=>n+p.paid+p.tds,0);
export const invoiceBalance=(s,i)=>i.amount==null?null:i.amount-settled(s,i.id);
export const invoiceStatus=(s,i)=>(s.invoiceEvents||[]).filter(e=>e.invoiceId===i.id).at(-1)?.status||'Open';
export function canFinanceAct(s,u,t,d,act){if(!can(s,u,t,act,d.kind))return false;const st=financeStatus(s,d);if(act==='submit')return st==='Draft'&&(u.superuser||d.createdBy===u.id);if(!u.superuser&&d.createdBy===u.id)return false;if(act==='review')return st==='Review';if(act==='reject')return !['Draft','Approved','Rejected'].includes(st);return act==='approve'&&!!approvalStage(s,u,t,d,s.financeEvents.map(e=>({...e,amendmentId:e.documentId})),d.kind);}
export function canCost(s,u,t){return !!u&&(u.superuser||roleList(s,u,t).some(r=>r.stage==='admin'))&&can(s,u,t,'view','cost_overview')&&fieldAccess(s,u,t,'amount','cost_overview')!=='hidden';}
export function costSummary(s,u){return s.tenants.filter(t=>!t.deleted&&canCost(s,u,t.id)&&(u.superuser||s.memberships.some(m=>m.userId===u.id&&m.tenantId===t.id&&m.roleIds.length))).map(t=>{const ex=(s.expenses||[]).filter(d=>d.tenantId===t.id&&financeStatus(s,d)==='Approved'),pay=(s.payments||[]).filter(d=>d.tenantId===t.id&&financeStatus(s,d)==='Approved'),inv=(s.invoices||[]).filter(i=>i.tenantId===t.id);const workOrders=s.orders.filter(o=>o.tenantId===t.id).reduce((n,o)=>n+effective(s,o),0),purchases=purchaseCost(s,t.id),additional=ex.filter(d=>!d.referenceId).reduce((n,d)=>n+d.amount,0);const categories=Object.fromEntries(expenseCategories.map(c=>[c,0]));for(const d of ex.filter(d=>!d.referenceId))categories[d.category]=(categories[d.category]||0)+d.amount;for(const p of s.purchaseOrders.filter(p=>p.tenantId===t.id&&status({events:s.purchaseEvents.map(e=>({...e,amendmentId:e.purchaseOrderId}))},p)==='Approved'))for(const l of p.lines){const c=l.kind==='rental'?'Equipment rental':'Material purchase';categories[c]+=l.total;}return {tenantId:t.id,project:t.name,workOrders,purchases,additional,total:workOrders+purchases+additional,recordedExpenses:ex.reduce((n,d)=>n+d.amount,0),paid:pay.reduce((n,d)=>n+d.paid,0),tds:pay.reduce((n,d)=>n+d.tds,0),outstanding:inv.reduce((n,i)=>n+invoiceBalance(s,i),0),categories};});}
export function redactFinance(s,u){s.costs=costSummary(s,u);for(const i of s.invoices||[])i.balance=invoiceBalance(s,i);for(const [key,form] of [['expenses','expense'],['payments','payment'],['invoices','payment']])s[key]=(s[key]||[]).filter(d=>s.tenants.some(t=>t.id===d.tenantId&&!t.deleted)&&(u.superuser||s.memberships.some(m=>m.userId===u.id&&m.tenantId===d.tenantId&&m.roleIds.length))&&can(s,u,d.tenantId,'view',form)).map(d=>{if(fieldAccess(s,u,d.tenantId,'amount',form)==='hidden')for(const k of ['amount','paid','tds','balance'])delete d[k];if(fieldAccess(s,u,d.tenantId,'description',form)==='hidden')delete d.description;if(fieldAccess(s,u,d.tenantId,'category',form)==='hidden')delete d.category;if(fieldAccess(s,u,d.tenantId,'remarks',form)==='hidden')delete d.remarks;if(fieldAccess(s,u,d.tenantId,'dates',form)==='hidden')for(const k of ['expenseDate','invoiceDate','paidDate','orderDate'])delete d[k];if(fieldAccess(s,u,d.tenantId,'reference',form)==='hidden')for(const k of ['referenceId','referenceType','orderId','orderNumber','vendorId','vendor','invoiceNumber','invoiceId','payee'])delete d[k];for(const k of Object.keys(d.data||{}))if(fieldAccess(s,u,d.tenantId,k,form)==='hidden')delete d.data[k];return d;});s.financeEvents=(s.financeEvents||[]).filter(e=>[...s.expenses,...s.payments].some(d=>d.id===e.documentId));s.invoiceEvents=(s.invoiceEvents||[]).filter(e=>s.invoices.some(i=>i.id===e.invoiceId));}
function amount(n,name){if(!Number.isSafeInteger(n)||n<0||n>1e14)throw Error(name+' must be a non-negative amount with at most two decimals.');return n;}
function need(s,u,t,f,act){if(!can(s,u,t,act,f)||financeFields.some(k=>fieldAccess(s,u,t,k,f)!=='edit'))throw Error('Form and field editing permissions are required.');}
function extras(s,u,t,d,f,old){const version=old?s.forms.find(x=>x.id===f&&x.version===old.formVersion):s.forms.filter(x=>x.id===f).sort((a,b)=>b.version-a.version)[0];if(!version)throw Error('Financial template not found.');const data=d.data||{};for(const k of Object.keys(data))if(!version.fields.some(f=>f.key===k))throw Error('Unknown custom field.');for(const x of version.fields){const v=String(data[x.key]??'').trim();if(x.required&&!v)throw Error(x.label+' is required.');if(v&&fieldAccess(s,u,t,x.key,f)!=='edit')throw Error('Custom field editing permission is required.');if(v&&x.type==='date'&&!validDate(v))throw Error(x.label+' needs a valid date.');if(v&&x.type==='number'&&!Number.isFinite(Number(v)))throw Error(x.label+' needs a number.');}return {data,formVersion:version.version};}
export function financeCommand(s,u,t,kind,d,log){
if(kind==='expense'||kind==='payment'){
 const list=kind==='expense'?s.expenses:s.payments,old=list.find(x=>x.id===d.id);if(d.id&&(!old||old.tenantId!==t))throw Error('Record not found in this project.');if(old&&(financeStatus(s,old)!=='Draft'||(!u.superuser&&old.createdBy!==u.id)))throw Error('Only the creator or superuser can edit a draft.');need(s,u,t,kind,old?'edit':'create');let body={id:old?.id||uid(),kind,tenantId:t,createdBy:old?.createdBy||u.id,createdAt:old?.createdAt||stamp(),approvalPolicy:2,creatorSuperuser:old?.creatorSuperuser??!!u.superuser,...extras(s,u,t,d,kind,old)};
 if(kind==='expense'){
  if(!d.description?.trim()||!d.category?.trim()||!d.payee?.trim()||!validDate(d.expenseDate)||amount(d.amount,'Expense amount')<=0)throw Error('Description, category, payee, date and a positive amount are required.');
  let referenceId=d.referenceId||'',referenceType=d.referenceType||'';
  if(referenceId){const record=(referenceType==='work_order'?s.orders:referenceType==='purchase_order'?s.purchaseOrders:[]).find(x=>x.id===referenceId&&x.tenantId===t);if(!record||!can(s,u,t,'view',referenceType)||(referenceType==='purchase_order'&&status({events:s.purchaseEvents.map(e=>({...e,amendmentId:e.purchaseOrderId}))},record)!=='Approved'))throw Error('Select a valid order from this project.');}else referenceType='';
  body={...body,amount:d.amount,description:d.description.trim(),category:d.category.trim(),payee:d.payee.trim(),expenseDate:d.expenseDate,referenceType,referenceId,remarks:String(d.remarks||'').trim()};
 }else{
  const inv=s.invoices.find(i=>i.id===d.invoiceId&&i.tenantId===t);if(!inv||invoiceStatus(s,inv)!=='Open')throw Error('Select an open invoice in this project.');const paid=amount(d.paid,'Paid amount'),tds=amount(d.tds,'TDS');if(paid+tds<=0||paid+tds>invoiceBalance(s,inv))throw Error('Paid amount + TDS must be positive and cannot exceed the invoice balance.');if(!validDate(d.paidDate)||d.paidDate<inv.invoiceDate)throw Error('Paid date must be valid and on or after the invoice date.');body={...body,invoiceId:inv.id,amount:paid+tds,paid,tds,paidDate:d.paidDate,remarks:String(d.remarks||'').trim()};
 }
 if(old)list[list.indexOf(old)]=body;else list.push(body);log(kind==='expense'?'Expense draft saved':'Payment draft saved',body.description||s.invoices.find(i=>i.id===body.invoiceId).invoiceNumber);
}else if(kind==='invoice'){
 need(s,u,t,'payment','create');const o=s.orders.find(o=>o.id===d.orderId&&o.tenantId===t),v=s.vendors.find(v=>v.id===o?.vendorId&&v.tenantId===t&&!v.deleted);if(!o||!v||!can(s,u,t,'view','work_order')||(v.onboardingStatus&&v.onboardingStatus!=='Active'))throw Error('Select a project work order with an active vendor.');if(!d.invoiceNumber?.trim()||d.invoiceNumber.trim().length>100||!d.description?.trim()||!d.category?.trim()||!validDate(d.invoiceDate)||amount(d.amount,'Invoice amount')<=0)throw Error('Invoice number, date, description, category and amount are required.');if(s.invoices.some(i=>i.tenantId===t&&i.vendorId===v.id&&i.invoiceNumber.toLowerCase()===d.invoiceNumber.trim().toLowerCase()))throw Error('This invoice number already exists for this vendor.');if(s.invoices.filter(i=>i.orderId===o.id).reduce((n,i)=>n+i.amount,0)+d.amount>effective(s,o))throw Error('Invoice values cannot exceed the effective work order value.');const i={id:uid(),tenantId:t,orderId:o.id,orderNumber:o.number,orderDate:o.orderDate||o.createdAt.slice(0,10),vendorId:v.id,vendor:v.name,invoiceNumber:d.invoiceNumber.trim(),invoiceDate:d.invoiceDate,amount:d.amount,description:d.description.trim(),category:d.category.trim(),remarks:String(d.remarks||'').trim(),createdBy:u.id,createdAt:stamp()};s.invoices.push(i);log('Vendor invoice registered',i.invoiceNumber);
}else if(kind==='finance-transition'){
 const record=[...s.expenses,...s.payments].find(x=>x.id===d.id&&x.tenantId===t);if(!record)throw Error('Financial record not found.');if(record.kind==='payment'&&['submit','approve'].includes(d.action)){const i=s.invoices.find(i=>i.id===record.invoiceId);if(invoiceStatus(s,i)!=='Open'||record.amount>invoiceBalance(s,i))throw Error('Approval blocked: invoice is closed or settlement exceeds its balance.');}
 const tmp={...s,orders:[{id:record.id,tenantId:t,number:record.id,base:0,formId:record.kind}],amendments:[{...record,orderId:record.id,delta:record.amount}],events:s.financeEvents.map(e=>({...e,amendmentId:e.documentId})),audit:[]};let e;try{e=transition(tmp,u,t,record.id,d.action);}catch(err){throw Error(err.message.replaceAll('amendment','financial record'));}delete e.amendmentId;s.financeEvents.push({...e,documentId:record.id});log(record.kind+' '+d.action+(e.stage?' · '+e.stage:''),record.id);
 if(record.kind==='payment'&&financeStatus(s,record)==='Approved'){const i=s.invoices.find(i=>i.id===record.invoiceId);if(invoiceBalance(s,i)===0)s.invoiceEvents.push({id:uid(),invoiceId:i.id,status:'Closed',reason:'Invoice fully settled',actorId:u.id,at:stamp()});}
}else if(kind==='invoice-status'){
 const i=s.invoices.find(i=>i.id===d.id&&i.tenantId===t);if(!i||!can(s,u,t,'amend','payment'))throw Error('Invoice amendment permission is required.');if(!['Open','Closed'].includes(d.status)||!d.reason?.trim()||d.status===invoiceStatus(s,i))throw Error('Select a different invoice status and enter a reason.');if(d.status==='Closed'&&invoiceBalance(s,i)!==0)throw Error('An invoice with an outstanding balance cannot be closed.');s.invoiceEvents.push({id:uid(),invoiceId:i.id,status:d.status,reason:d.reason.trim(),actorId:u.id,at:stamp()});log('Invoice status amended',i.invoiceNumber);
}else return false;return true;}
export function onboardingCommand(s,u,t,kind,d,log){
 if(!['onboarding-save','onboarding-transition'].includes(kind))return false;
 if(!can(s,u,t,kind==='onboarding-save'?(d.id?'edit':'create'):d.action==='submit'?'submit':'approve','vendor_onboarding'))throw Error('Vendor onboarding permission is required.');
 const old=s.vendors.find(v=>v.id===d.id&&v.tenantId===t&&!v.deleted);
 if(d.id&&!old)throw Error('Vendor not found.');
 if(kind==='onboarding-save'){
  if(['name','trade','vendorType','contactName','phone','email','gstin','pan','address','notes'].some(k=>fieldAccess(s,u,t,k,'vendor_onboarding')!=='edit'))throw Error('Vendor onboarding field editing permission is required.');
  if(old&&(old.onboardingStatus!=='Draft'||(!u.superuser&&old.createdBy!==u.id)))throw Error('Only the creator or superuser can edit an onboarding draft.');
  const v={id:old?.id||uid(),tenantId:t,deleted:false,createdBy:old?.createdBy||u.id,createdAt:old?.createdAt||stamp(),updatedAt:stamp(),onboardingStatus:'Draft'};
  for(const k of ['name','trade','vendorType','contactName','phone','email','gstin','pan','address','notes']){v[k]=String(d[k]||'').trim();if(v[k].length>1000)throw Error('Vendor details exceed allowed length.');}
  if(!v.name||!v.trade||!v.vendorType||!v.contactName||!v.address||!/^\+?[0-9 ()-]{7,22}$/.test(v.phone)||v.phone.replace(/\D/g,'').length<7||v.phone.replace(/\D/g,'').length>15)throw Error('Name, type, trade, contact, address and a valid phone number are required.');if(v.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.email))throw Error('Enter a valid email address.');v.gstin=v.gstin.toUpperCase();v.pan=v.pan.toUpperCase();if(v.gstin&&!/^[A-Z0-9]{15}$/.test(v.gstin))throw Error('GSTIN must contain 15 letters or digits.');if(v.pan&&!/^[A-Z0-9]{10}$/.test(v.pan))throw Error('PAN must contain 10 letters or digits.');if(old)s.vendors[s.vendors.indexOf(old)]=v;else s.vendors.push(v);log('Vendor onboarding draft saved',v.name);
 }else{
  if(d.action==='submit'){if(old.onboardingStatus!=='Draft'||(!u.superuser&&old.createdBy!==u.id))throw Error('Only an onboarding draft can be submitted by its creator.');old.onboardingStatus='Submitted';}else{if(!u.superuser||old.onboardingStatus!=='Submitted')throw Error('The superuser must review a submitted vendor.');if(d.action==='activate')old.onboardingStatus='Active';else if(['return','reject'].includes(d.action)&&d.reason?.trim())old.onboardingStatus=d.action==='return'?'Draft':'Rejected';else throw Error('Choose an action and provide a reason for returning or rejecting.');}old.updatedAt=stamp();log('Vendor onboarding '+d.action+(d.reason?' · '+d.reason:''),old.name);
 }return true;
}
