import {createApp} from 'vue';
import {createVuetify} from 'vuetify';
import * as components from 'vuetify/components';
import * as directives from 'vuetify/directives';
import 'vuetify/styles';
import '@mdi/font/css/materialdesignicons.css';
import App from './App.vue';
import './style.css';
import {themeOptions,applyPalette} from './theme.js';
applyPalette(document.documentElement);
const vuetify=createVuetify({components,directives,theme:themeOptions,defaults:{VBtn:{rounded:'lg',elevation:0},VTextField:{variant:'outlined',density:'comfortable'},VSelect:{variant:'outlined',density:'comfortable'},VTextarea:{variant:'outlined',density:'comfortable'}}});
createApp(App).use(vuetify).mount('#app');
