<script setup>
import {ref,computed} from 'vue';
import {can,fieldAccess} from './domain.js';
import {vendorTrades,vendorTypes} from './finance.js';
const props=defineProps(['state','user','tenantId','execute','busy','failure']);
const dialog=ref(''),selected=ref(''),form=ref({}),error=ref(''),formRef=ref(null);
const fields=['name','trade','vendorType','contactName','phone','email','gstin','pan','address','notes'];
const allowed=a=>can(props.state,props.user,props.tenantId,a,'vendor_onboarding');
const editable=computed(()=>fields.every(k=>fieldAccess(props.state,props.user,props.tenantId,k,'vendor_onboarding')==='edit'));
const vendors=computed(()=>props.state.vendors.filter(v=>v.tenantId===props.tenantId&&!v.deleted&&allowed('view')));
const active=computed(()=>vendors.value.find(v=>v.id===selected.value));
const creator=v=>props.user.superuser||v.createdBy===props.user.id;
const required=v=>!!String(v??'').trim()||'Required';
const email=v=>!v||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)||'Enter a valid email';
const phone=v=>/^\+?[0-9 ()-]{7,22}$/.test(v||'')&&v.replace(/\D/g,'').length>=7&&v.replace(/\D/g,'').length<=15||'Enter a valid phone number';
function open(type,v){error.value='';dialog.value=type;form.value=type==='draft'?(v?JSON.parse(JSON.stringify(v)):Object.fromEntries(fields.map(k=>[k,'']))):{id:v.id,reason:''};}
async function save(){try{error.value='';if(formRef.value&&!(await formRef.value.validate()).valid)return;const r=await props.execute(dialog.value==='draft'?'onboarding-save':'onboarding-transition',dialog.value==='draft'?form.value:{...form.value,action:dialog.value},'Vendor onboarding updated',false);if(r)dialog.value='';}catch(e){error.value=e.message;}}
async function action(v,a){await props.execute('onboarding-transition',{id:v.id,action:a},'Vendor onboarding updated',false);}
</script>
<template>
<div class="workflow-banner"><v-icon color="primary">mdi-account-plus-outline</v-icon><div><strong>Vendor onboarding</strong><p>Choose a type and trade from the suggestions or enter your own. Save a draft, submit it, then activate it as Superuser before creating new orders.</p></div></div>
<div class="stats-grid procurement-stats"><div v-for="stage in ['Draft','Submitted','Active']" :key="stage" class="stat-card" :class="stage==='Submitted'?'primary-stat':''"><div class="stat-label">{{stage==='Submitted'?'Awaiting activation':stage+' vendors'}}</div><strong>{{vendors.filter(v=>(v.onboardingStatus||'Active')===stage).length}}</strong><span>{{stage==='Active'?'Available for new work and purchase orders.':stage==='Submitted'?'Superuser review required.':'Prepared profiles awaiting submission.'}}</span></div></div>
<section class="panel"><div class="panel-top"><div><h2>Project vendor intake</h2><p>Profiles are specific to this project. Vendors may recur in other projects.</p></div><v-btn v-if="allowed('create')&&editable" color="primary" prepend-icon="mdi-plus" @click="open('draft')">Onboard vendor</v-btn></div><div class="table-scroll"><table class="orders-table"><thead><tr><th>VENDOR / TYPE</th><th>TRADE</th><th>CONTACT</th><th>STATUS</th><th></th></tr></thead><tbody><tr v-for="v in vendors" :key="v.id"><td><strong>{{v.name||'Restricted'}}</strong><span class="cell-secondary">{{v.vendorType||'—'}}</span></td><td>{{v.trade||'Restricted'}}</td><td>{{v.contactName||'Restricted'}}<span class="cell-secondary">{{v.phone||'—'}} · {{v.email||'—'}}</span></td><td><span class="status-badge" :class="v.onboardingStatus==='Active'?'green':'amber'">{{v.onboardingStatus||'Active'}}</span></td><td><v-btn variant="text" size="small" @click="selected=v.id">View</v-btn><v-btn v-if="v.onboardingStatus==='Draft'&&creator(v)&&allowed('edit')&&editable" variant="text" size="small" @click="open('draft',v)">Edit draft</v-btn></td></tr><tr v-if="!vendors.length"><td colspan="5" class="empty-state">No vendor profiles available with your current permissions.</td></tr></tbody></table></div></section>
<v-dialog :model-value="!!active" @update:model-value="v=>{if(!v)selected=''}" max-width="740"><v-card v-if="active"><v-card-title class="dialog-title">{{active.name||'Vendor profile'}}<v-btn icon="mdi-close" variant="text" aria-label="Close profile" @click="selected=''"/></v-card-title><v-card-text><span class="status-badge amber">{{active.onboardingStatus||'Active'}}</span><div class="custom-data mt-5"><div v-for="k in fields.filter(k=>active[k]!=null)" :key="k"><small>{{k==='vendorType'?'Vendor type':k==='contactName'?'Contact person':k}}</small><strong>{{active[k]||'—'}}</strong></div></div><div class="approval-actions"><v-btn v-if="active.onboardingStatus==='Draft'&&creator(active)&&allowed('submit')" color="primary" :loading="busy" @click="action(active,'submit')">Submit for activation</v-btn><template v-if="active.onboardingStatus==='Submitted'&&user.superuser"><v-btn color="primary" :loading="busy" @click="action(active,'activate')">Activate vendor</v-btn><v-btn variant="outlined" @click="open('return',active)">Return to draft</v-btn><v-btn color="error" variant="outlined" @click="open('reject',active)">Reject</v-btn></template></div><div v-for="e in state.audit.filter(e=>e.tenantId===tenantId&&e.target===active.name&&e.action.startsWith('Vendor onboarding'))" :key="e.id" class="event-line"><v-icon size="16">mdi-history</v-icon>{{e.action}} · {{new Date(e.at).toLocaleString('en-IN')}}</div><v-alert v-if="failure" type="error" class="mt-4">{{failure}}</v-alert></v-card-text></v-card></v-dialog>
<v-dialog :model-value="!!dialog" @update:model-value="v=>{if(!v)dialog=''}" max-width="740"><v-card><v-card-title class="dialog-title">{{dialog==='draft'?'Vendor onboarding draft':dialog==='return'?'Return vendor to draft':'Reject vendor'}}<v-btn icon="mdi-close" variant="text" aria-label="Close form" @click="dialog=''"/></v-card-title><v-card-text><v-alert v-if="error||failure" type="error" class="mb-4">{{error||failure}}</v-alert><v-form ref="formRef" @submit.prevent="save"><template v-if="dialog==='draft'"><v-text-field v-model="form.name" label="Vendor name *" :rules="[required]"/><div class="form-two-columns"><v-combobox v-model="form.vendorType" :items="vendorTypes" label="Vendor type · choose or type *" :rules="[required]"/><v-combobox v-model="form.trade" :items="vendorTrades" label="Trade · choose or type *" :rules="[required]"/></div><v-text-field v-model="form.contactName" label="Contact person *" :rules="[required]"/><div class="form-two-columns"><v-text-field v-model="form.phone" label="Phone *" :rules="[phone]"/><v-text-field v-model="form.email" label="Email" :rules="[email]"/><v-text-field v-model="form.gstin" label="GSTIN (optional)" :rules="[v=>!v||/^[A-Za-z0-9]{15}$/.test(v)||'Use 15 letters or digits']"/><v-text-field v-model="form.pan" label="PAN (optional)" :rules="[v=>!v||/^[A-Za-z0-9]{10}$/.test(v)||'Use 10 letters or digits']"/></div><v-textarea v-model="form.address" label="Address *" rows="2" :rules="[required]"/><v-textarea v-model="form.notes" label="Onboarding notes" rows="2"/></template><v-textarea v-else v-model="form.reason" label="Reason *" :rules="[required]" rows="3"/></v-form></v-card-text><v-card-actions class="dialog-actions"><v-btn @click="dialog=''">Cancel</v-btn><v-spacer/><v-btn color="primary" :loading="busy" @click="save">{{dialog==='draft'?'Save draft':'Record decision'}}</v-btn></v-card-actions></v-card></v-dialog>
</template>
