import {can,fieldAccess,approvalStage,status,transition,uid,stamp} from './domain.js';
export const purchaseFields=['amount','description','materials','order_date'];
export const inventoryFields=['materials','quantity'];
export const quantity=n=>{if(!/^\d+(\.\d{1,3})?$/.test(String(n)))throw Error('Quantity must be positive with at most three decimals.');const v=Math.round(Number(n)*1000);if(!Number.isSafeInteger(v)||v<=0||v>1e9)throw Error('Quantity is outside the supported range.');return v;};
export const qty=n=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:3}).format(n/1000);
export const poStatus=(s,p)=>status({events:(s.purchaseEvents||[]).map(e=>({...e,amendmentId:e.purchaseOrderId}))},p);
export const balance=(s,t,lot)=>s.stockMovements.filter(m=>m.tenantId===t&&m.lotId===lot).reduce((n,m)=>n+m.quantityMilli,0);
export function inventory(s,t){return s.stockLots.filter(l=>s.stockMovements.some(m=>m.tenantId===t&&m.lotId===l.id)).map(l=>({...l,available:s.stockMovements.some(m=>m.tenantId===t&&m.lotId===l.id&&m.quantityMilli==null)?null:balance(s,t,l.id)})).filter(l=>l.available===null||l.available>0);}
export const purchaseCost=(s,t)=>s.purchaseOrders.filter(p=>p.tenantId===t&&poStatus(s,p)==='Approved').reduce((n,p)=>n+(p.total??0),0);
export function canPOAct(s,u,t,p,action){if(!can(s,u,t,action,'purchase_order'))return false;const st=poStatus(s,p);if(action==='submit')return st==='Draft'&&(p.createdBy===u.id||u.superuser);if(p.createdBy===u.id&&!u.superuser)return false;if(action==='review')return st==='Review';if(action==='reject')return !['Draft','Approved','Rejected'].includes(st);if(action==='approve')return !!approvalStage(s,u,t,p,s.purchaseEvents.map(e=>({...e,amendmentId:e.purchaseOrderId})),'purchase_order');return false;}
export const purchaseApprovals=(s,p)=>s.purchaseEvents.filter(e=>e.purchaseOrderId===p.id&&e.action==='approve');
export function procurementCommand(s,u,t,kind,d,log){
if(kind==='purchase-order'){
const old=s.purchaseOrders.find(p=>p.id===d.id);if(d.id&&(!old||old.tenantId!==t))throw Error('Purchase order not found.');if(old&&(poStatus(s,old)!=='Draft'||(!u.superuser&&old.createdBy!==u.id)))throw Error('Only the creator or superuser can edit a draft.');
if(!can(s,u,t,old?'edit':'create','purchase_order')||purchaseFields.some(k=>fieldAccess(s,u,t,k,'purchase_order')!=='edit'))throw Error('Purchase order and field editing permissions are required.');
const v=s.vendors.find(v=>v.id===d.vendorId&&v.tenantId===t&&!v.deleted);if(!v||(v.onboardingStatus&&v.onboardingStatus!=='Active'))throw Error('Select an active project vendor.');if(!d.number?.trim()||!d.description?.trim())throw Error('Purchase order number and description are required.');if(s.purchaseOrders.some(p=>p.id!==old?.id&&p.tenantId===t&&p.number===d.number.trim()))throw Error('Purchase order number already exists in this project.');
if(!Array.isArray(d.lines)||!d.lines.length||d.lines.length>100)throw Error('Add 1–100 material lines.');
const lines=d.lines.map(l=>{if(!l.material?.trim()||!l.unit?.trim()||!['purchase','rental'].includes(l.kind)||!Number.isSafeInteger(l.quantityMilli)||l.quantityMilli<=0||l.quantityMilli>1e9||!Number.isSafeInteger(l.rate)||l.rate<0||l.rate>1e11)throw Error('Each line needs a material, unit, quantity, type and non-negative rate.');const total=Number((BigInt(l.quantityMilli)*BigInt(l.rate)+500n)/1000n);if(!Number.isSafeInteger(total)||total>1e14)throw Error('Line total exceeds the supported range.');return {id:uid(),material:l.material.trim(),unit:l.unit.trim(),kind:l.kind,quantityMilli:l.quantityMilli,rate:l.rate,total};});const total=lines.reduce((n,l)=>n+l.total,0);if(total>1e14)throw Error('Purchase order exceeds the supported range.');const f=s.forms.filter(f=>f.id==='purchase_order').sort((a,b)=>b.version-a.version)[0];const version=old?s.forms.find(f=>f.id==='purchase_order'&&f.version===old.formVersion):f;const known=new Set(version.fields.map(f=>f.key));for(const k of Object.keys(d.data||{}))if(!known.has(k))throw Error('Unknown custom field: '+k);for(const field of version.fields){if(fieldAccess(s,u,t,field.key,'purchase_order')!=='edit'&&String(d.data?.[field.key]??'').trim())throw Error('You cannot edit '+field.label);if(field.required&&!String(d.data?.[field.key]??'').trim())throw Error(field.label+' is required.');if(field.type==='number'&&d.data?.[field.key]&&!Number.isFinite(Number(d.data[field.key])))throw Error(field.label+' must be a number.');if(field.type==='date'&&d.data?.[field.key]&&(!/^\d{4}-\d{2}-\d{2}$/.test(d.data[field.key])||!Number.isFinite(Date.parse(d.data[field.key]))||new Date(d.data[field.key]).toISOString().slice(0,10)!==d.data[field.key]))throw Error(field.label+' must be a date.');}
const orderDate=d.orderDate||old?.orderDate||old?.createdAt?.slice(0,10)||stamp().slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(orderDate)||!Number.isFinite(Date.parse(orderDate))||new Date(orderDate).toISOString().slice(0,10)!==orderDate)throw Error('Enter a valid purchase order date.');const p={orderDate,id:old?.id||uid(),tenantId:t,number:d.number.trim(),description:d.description.trim(),vendorId:v.id,vendor:v.name,vendorSnapshot:{...v},lines,total,data:d.data||{},formVersion:version.version,createdBy:old?.createdBy||u.id,createdAt:old?.createdAt||stamp(),updatedAt:stamp(),approvalPolicy:old?.approvalPolicy??2,creatorSuperuser:old?.creatorSuperuser??!!u.superuser};if(old)s.purchaseOrders[s.purchaseOrders.indexOf(old)]=p;else s.purchaseOrders.push(p);log(old?'Purchase order draft updated':'Purchase order draft created',p.number);
}else if(kind==='purchase-transition'){
const p=s.purchaseOrders.find(p=>p.id===d.id&&p.tenantId===t);if(!p)throw Error('Purchase order not found.');const events=s.purchaseEvents.map(e=>({...e,amendmentId:e.purchaseOrderId}));const tmp={...s,orders:[{id:p.id,tenantId:t,number:p.number,base:0,formId:'purchase_order'}],amendments:[{id:p.id,orderId:p.id,delta:p.total,createdBy:p.createdBy,approvalPolicy:p.approvalPolicy,creatorSuperuser:p.creatorSuperuser}],events,audit:[]};const e=transition(tmp,u,t,p.id,d.action);delete e.amendmentId;s.purchaseEvents.push({...e,purchaseOrderId:p.id});log('Purchase order '+d.action+(e.stage?' · '+e.stage:''),p.number);
}else if(kind==='purchase-receive'){
const p=s.purchaseOrders.find(p=>p.id===d.id&&p.tenantId===t);if(!p||poStatus(s,p)!=='Approved')throw Error('Receive only an approved purchase order.');if(!can(s,u,t,'view','purchase_order')||!can(s,u,t,'create','inventory')||inventoryFields.some(k=>fieldAccess(s,u,t,k,'inventory')!=='edit'))throw Error('Inventory receipt permission is required.');const l=p.lines.find(l=>l.id===d.lineId&&l.kind==='purchase');if(!l)throw Error('Rental lines cannot enter owned inventory.');const received=s.stockMovements.filter(m=>m.kind==='receipt'&&m.lineId===l.id).reduce((n,m)=>n+m.quantityMilli,0);if(!Number.isSafeInteger(d.quantityMilli)||d.quantityMilli<=0||d.quantityMilli>l.quantityMilli-received)throw Error('Receipt exceeds the remaining ordered quantity.');let lot=s.stockLots.find(lot=>lot.lineId===l.id);if(!lot){lot={id:uid(),lineId:l.id,purchaseOrderId:p.id,originTenantId:t,material:l.material,unit:l.unit,createdAt:stamp()};s.stockLots.push(lot);}s.stockMovements.push({id:uid(),lotId:lot.id,lineId:l.id,tenantId:t,kind:'receipt',quantityMilli:d.quantityMilli,actorId:u.id,at:stamp()});log('Purchased materials received into inventory',p.number+' · '+l.material);
}else if(kind==='inventory-transfer'||kind==='inventory-issue'){
if(!can(s,u,t,'edit','inventory')||inventoryFields.some(k=>fieldAccess(s,u,t,k,'inventory')!=='edit'))throw Error('Inventory editing permission is required.');const l=s.stockLots.find(l=>l.id===d.lotId);if(!l||!Number.isSafeInteger(d.quantityMilli)||d.quantityMilli<=0||d.quantityMilli>balance(s,t,l.id))throw Error('Quantity exceeds available project stock.');if(!d.reason?.trim())throw Error('A reason is required.');const transferId=uid();if(kind==='inventory-transfer'){if(d.targetTenantId===t||!s.tenants.some(p=>p.id===d.targetTenantId&&!p.deleted)||!can(s,u,d.targetTenantId,'create','inventory')||inventoryFields.some(k=>fieldAccess(s,u,d.targetTenantId,k,'inventory')!=='edit'))throw Error('Select another active project where you can receive inventory.');if(!u.superuser&&!s.memberships.some(m=>m.userId===u.id&&m.tenantId===d.targetTenantId&&m.roleIds.length))throw Error('Target project access is required.');s.stockMovements.push({id:uid(),lotId:l.id,tenantId:d.targetTenantId,kind:'transfer-in',counterpartyId:t,transferId,quantityMilli:d.quantityMilli,reason:d.reason,actorId:u.id,at:stamp()});s.audit.push({id:uid(),tenantId:d.targetTenantId,actorId:u.id,action:'Inventory transfer received',target:l.material,at:stamp()});}s.stockMovements.push({id:uid(),lotId:l.id,tenantId:t,kind:kind==='inventory-transfer'?'transfer-out':'issue',counterpartyId:d.targetTenantId||'',transferId,quantityMilli:-d.quantityMilli,reason:d.reason,actorId:u.id,at:stamp()});log(kind==='inventory-transfer'?'Unused stock transferred':'Stock issued for use',l.material);
}else return false;return true;
}
