<script setup>
import {ref} from 'vue';
import {money,effective} from './domain.js';
import {purchaseCost} from './procurement.js';
const props=defineProps(['state','user','busy','execute','failure']);const emit=defineEmits(['select']);const dialog=ref(''),form=ref({});
function open(kind,p){form.value=p?{...p}:{name:'',code:'',location:''};dialog.value=kind;}
async function save(){const result=await props.execute(dialog.value==='delete'?'tenant-delete':'tenant',{...form.value},dialog.value==='delete'?'Project deleted from active use':'Project saved');if(result?.ok)dialog.value='';}
const cost=p=>props.state.orders.filter(o=>o.tenantId===p.id).reduce((n,o)=>n+effective(props.state,o),0)+purchaseCost(props.state,p.id);
</script>
<template><section v-if="user.superuser" class="panel"><div class="panel-top"><div><h2>All projects</h2><p>Only the platform superuser can create, edit or delete projects.</p></div><v-btn color="primary" prepend-icon="mdi-plus" @click="open('edit')">Add project</v-btn></div><div class="table-scroll"><table class="orders-table"><thead><tr><th>PROJECT</th><th>LOCATION</th><th>COMMITTED COST</th><th>STATUS</th><th>MANAGE</th></tr></thead><tbody><tr v-for="p in state.tenants" :key="p.id"><td><button v-if="!p.deleted" class="order-link" @click="emit('select',p.id)">{{p.name}}</button><strong v-else>{{p.name}}</strong><span class="cell-secondary">{{p.code}}</span></td><td>{{p.location}}</td><td>{{money(cost(p))}}<span class="cell-secondary">Work orders + approved purchases and rentals</span></td><td><span :class="['status-badge',p.deleted?'gray':'green']">{{p.deleted?'Deleted · history retained':'Active'}}</span></td><td><div v-if="!p.deleted" class="heading-actions"><v-btn size="small" variant="outlined" prepend-icon="mdi-pencil-outline" @click="open('edit',p)">Edit</v-btn><v-btn size="small" variant="text" color="error" prepend-icon="mdi-delete-outline" @click="open('delete',p)">Delete</v-btn></div></td></tr><tr v-if="!state.tenants.length"><td colspan="5" class="empty-state">Add your first project to begin.</td></tr></tbody></table></div></section>
<v-dialog :model-value="!!dialog" @update:model-value="v=>{if(!v)dialog=''}" max-width="580"><v-card><v-card-title class="dialog-title">{{dialog==='delete'?'Delete project':form.id?'Edit project':'Add project'}}<v-btn icon="mdi-close" variant="text" aria-label="Close project dialog" @click="dialog=''"/></v-card-title><v-card-text><v-alert v-if="failure" type="error" class="mb-4">{{failure}}</v-alert><template v-if="dialog==='delete'"><p>Delete <strong>{{form.name}}</strong> from active use?</p><v-alert type="info" variant="tonal" class="mt-5">Financial records, RERA account numbers and audit history are retained. Transfer or issue any remaining inventory first. Users will lose access to this project.</v-alert></template><template v-else><v-text-field v-model="form.name" label="Project name *"/><v-text-field v-model="form.code" label="Project code *"/><v-text-field v-model="form.location" label="City, state"/></template></v-card-text><v-card-actions class="dialog-actions"><v-btn @click="dialog=''">Cancel</v-btn><v-spacer/><v-btn variant="flat" :color="dialog==='delete'?'error':'primary'" :loading="busy" @click="save">{{dialog==='delete'?'Delete project':'Save project'}}</v-btn></v-card-actions></v-card></v-dialog></template>
