export function seedSuite(s){
s.forms.push({id:"project",name:"Project",version:1,fields:[]});
const fields={quotation_request:['description','reference'],vendor_quotation:['amount','description','vendor','terms'],quotation_selection:['reference','reason','amount'],vendor_feedback:['vendor','reference','ratings','comments','dates'],project_plan:['amount','targets','dates'],progress:['reference','progress','dates','comments'],sale:['amount','customer','unit','status','dates'],collection:['amount','reference','dates','remarks'],dashboard:['progress','cash','sales','budget'],vendor_reporting:['amount','ratings','reference']};
for(const [id,keys]of Object.entries(fields))s.forms.push({id,name:{quotation_request:'Quotation Work Package',vendor_quotation:'Vendor Quotation',quotation_selection:'Quotation Selection',vendor_feedback:'Vendor Feedback',project_plan:'Project Budget & Targets',progress:'Work Progress',sale:'Unit Sales',collection:'Cash Collections',dashboard:'CRM Dashboard',vendor_reporting:'Vendor Reporting'}[id],version:1,fields:[]});
for(const r of s.roles){const admin=r.stage==='admin',finance=r.stage==='finance',manager=r.stage==='manager';for(const [f,keys]of Object.entries(fields)){if(f==='dashboard'){r.permissions[f]={actions:['view'],fields:{progress:'view',cash:admin||finance?'view':'hidden',sales:admin||finance?'view':'hidden',budget:admin?'view':'hidden'}};continue;}if(f==='vendor_reporting'){r.permissions[f]={actions:['view'],fields:{amount:admin||finance?'view':'hidden',ratings:'view',reference:'view'}};continue;}const edit=admin||(['quotation_request','vendor_quotation','quotation_selection','vendor_feedback','progress'].includes(f)&&manager)||(['quotation_request','vendor_quotation','quotation_selection','sale','collection'].includes(f)&&finance);r.permissions[f]={actions:edit?['view','create','edit','submit','review','approve','reject']:['vendor_feedback','progress'].includes(f)?['view']:[],fields:Object.fromEntries(keys.map(k=>[k,edit?'edit':r.id==='engineer'&&k==='amount'?'hidden':'view']))};}for(const k of ['quotation','contract'])r.permissions.work_order.fields[k]=r.id==='engineer'?(k==='contract'?'hidden':'view'):'edit';for(const k of ['reference','purpose'])r.permissions.purchase_order.fields[k]=r.id==='engineer'?'view':'edit';}
s.suiteRecords=[];s.suiteEvents=[];s.orderEvents=[];s.attachments=[];
const base=(id,kind,body,at='2026-10-01T08:00:00Z')=>({id,kind,tenantId:'t1',createdBy:'u1',createdAt:at,updatedAt:at,formVersion:1,data:{},...body});
s.suiteRecords.push(base('rfq1','rfq',{title:'Tower B plastering package',description:'Internal plastering for Tower B, floors 1–5',contractType:'Labour',referenceOrderId:'w4'}));
for(const [i,v,amount,days,quality,experience]of [[1,'v1',9000000,35,4,5],[2,'v4',9800000,28,5,4],[3,'v3',8500000,45,3,3]])s.suiteRecords.push(base('quote'+i,'quotation',{rfqId:'rfq1',vendorId:v,vendor:s.vendors.find(x=>x.id===v).name,number:'QT-SKY-'+String(i).padStart(3,'0'),quotationDate:'2026-10-01',amount,deliveryDays:days,creditDays:i===1?30:i===2?45:15,description:'Internal plastering · Tower B',terms:'Payment against measured work; rates include tax.'}));
s.suiteRecords.push(base('award1','award',{rfqId:'rfq1',quotationId:'quote1',amount:9000000,reason:'Competitive value and deeper relevant experience; selected over the faster bidder.',approvalPolicy:2,creatorSuperuser:true}));
s.suiteEvents.push({id:'se1',documentId:'award1',action:'submit',stage:'',actorId:'u1',at:'2026-10-01T09:00:00Z'},{id:'se2',documentId:'award1',action:'approve',stage:'superuser',actorId:'u1',at:'2026-10-01T10:00:00Z'});
s.suiteRecords.push(base('plan1','project_plan',{budget:300000000,salesTarget:1200000000,unitTarget:20,startDate:'2026-09-01',endDate:'2027-06-30',monthlyTargets:[{month:'2026-09',cash:80000000,progress:22},{month:'2026-10',cash:120000000,progress:45},{month:'2026-11',cash:160000000,progress:60}]}));
for(const [i,orderId,percent]of [[1,'w1',22],[2,'w2',16],[3,'w3',12],[4,'w4',5]])s.suiteRecords.push(base('progress-sep'+i,'progress',{orderId,percent,date:'2026-09-30',comments:'September site measurements · illustrative sample'},'2026-09-30T08:00:00Z'));
for(const [i,orderId,percent]of [[1,'w1',48],[2,'w2',32],[3,'w3',28],[4,'w4',15]])s.suiteRecords.push(base('progress'+i,'progress',{orderId,percent,date:'2026-10-06',comments:'Site-measured completion · illustrative sample'}));
for(const [id,unit,customer,status,amount,date]of [['sale1','A-101','Priya Sharma','Booked',650000000,'2026-09-10'],['sale2','A-102','Arun Mehta','Booked',700000000,'2026-09-18'],['sale3','B-201','Neha Rao','Reserved',720000000,'2026-10-02'],['sale4','B-202','Sanjay Patel','Lead',680000000,'2026-10-05']])s.suiteRecords.push(base(id,'sale',{unit,customer,status,amount,date}));
for(const [id,saleId,amount,date,reference]of [['cash1','sale1',30000000,'2026-09-20','RCPT-SKY-001'],['cash2','sale2',20000000,'2026-09-25','RCPT-SKY-002'],['cash3','sale1',40000000,'2026-10-04','RCPT-SKY-003'],['cash4','sale2',25000000,'2026-10-06','RCPT-SKY-004']])s.suiteRecords.push(base(id,'collection',{saleId,amount,date,reference,remarks:'Booked-unit collection · sample'}));
s.suiteRecords.push(base('feedback1','vendor_feedback',{vendorId:'v1',vendor:'Sri Sai Constructions',orderId:'w1',quality:4,timeliness:4,safety:5,communication:4,date:'2026-10-05',comments:'Good structural quality; improve advance coordination of deliveries.'}));
s.purchaseOrders[0].orderId='w1';s.purchaseOrders[0].orderNumber='WO-SKY-001';s.purchaseOrders[0].purpose='TMT steel for Tower A slab reinforcement; mixer for concrete placement.';s.purchaseOrders[0].lines.forEach(l=>l.purpose=l.kind==='rental'?'Concrete placement for Tower A slabs':'Slab reinforcement for Tower A');
s.vendors.find(v=>v.id==='v7').pan='ABCDE1234F';
}
