import {can,fieldAccess,status,transition,uid,stamp,approvalStage} from './domain.js';
import {poStatus} from './procurement.js';import {metadata,redactMetadata} from './metadata.js';
export const contractTypes=['Material construction','Labour'];
export const suiteFields={rfq:['description','reference'],quotation:['amount','description','vendor','terms'],award:['reference','reason','amount'],vendor_feedback:['vendor','reference','ratings','comments','dates'],project_plan:['amount','targets','dates'],progress:['reference','progress','dates','comments'],sale:['amount','customer','unit','status','dates'],collection:['amount','reference','dates','remarks']};
export const formForKind=k=>k==='award'?'quotation_selection':k==='rfq'?'quotation_request':k==='quotation'?'vendor_quotation':k;
export const suiteStatus=(s,d)=>status({events:(s.suiteEvents||[]).map(e=>({...e,amendmentId:e.documentId}))},d);
export const orderStatus=(s,o)=>o.workflowEnabled?status({events:(s.orderEvents||[]).map(e=>({...e,amendmentId:e.orderId}))},o):'Approved';
export const suiteRows=(s,k,t)=>(s.suiteRecords||[]).filter(d=>d.kind===k&&(!t||d.tenantId===t));
export function requireEdit(s,u,t,f,keys,a='create'){if(!can(s,u,t,a,f)||keys.some(k=>fieldAccess(s,u,t,k,f)!=='edit'))throw Error('Form and core-field editing permissions are required.');}
const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||'')&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
const integer=(v,min=0,max=1e14)=>{if(!Number.isSafeInteger(v)||v<min||v>max)throw Error('Enter a value within the supported range.');return v;};
const required=(v,name)=>{if(!String(v||'').trim())throw Error(name+' is required.');return String(v).trim();};
export function suiteRecord(s,u,t,k,d){const f=formForKind(k),old=s.suiteRecords.find(x=>x.id===d.id);if(d.id&&(!old||old.tenantId!==t||old.kind!==k))throw Error('Record not found in this project.');if(old&&(!u.superuser&&old.createdBy!==u.id))throw Error('Only the creator or Superuser can edit this record.');if(old&&(k==='award'||s.suiteRecords.some(a=>a.kind==='award'&&a.quotationId===old.id)||s.orders.some(o=>o.quotationId===old.id)))throw Error('Selected quotation and decision history are retained; create a new revision.');requireEdit(s,u,t,f,suiteFields[k],old?'edit':'create');let m={id:old?.id||uid(),kind:k,tenantId:t,createdBy:old?.createdBy||u.id,createdAt:old?.createdAt||stamp(),updatedAt:stamp(),...metadata(s,u,t,f,d,old)};
 const order=id=>s.orders.find(o=>o.id===id&&o.tenantId===t);
 const vendor=id=>s.vendors.find(v=>v.id===id&&v.tenantId===t&&!v.deleted&&(!v.onboardingStatus||v.onboardingStatus==='Active'));
 if(k==='rfq'){if(old&&suiteRows(s,'quotation').some(q=>q.rfqId===old.id))throw Error('A work package with quotations is retained; create a new package.');m.title=required(d.title,'Work package');m.description=required(d.description,'Scope');m.contractType=required(d.contractType,'Contract type');if(!contractTypes.includes(m.contractType))throw Error('Choose a supported contract type.');m.referenceOrderId=d.referenceOrderId||'';if(m.referenceOrderId&&(!order(m.referenceOrderId)||!can(s,u,t,'view','work_order')))throw Error('Select a project work order.');}
 if(k==='quotation'){const r=suiteRows(s,'rfq',t).find(x=>x.id===d.rfqId);if(!r||!can(s,u,t,'view','quotation_request'))throw Error('Select a quotation work package.');if(suiteRows(s,'award',t).some(a=>a.rfqId===r.id&&!['Rejected'].includes(suiteStatus(s,a))))throw Error('This package has a selection in progress or approved.');const v=vendor(d.vendorId);if(!v)throw Error('Select an active project vendor.');m.rfqId=r.id;m.vendorId=v.id;m.vendor=v.name;m.number=required(d.number,'Quotation number');if(suiteRows(s,'quotation',t).some(q=>q.id!==m.id&&q.vendorId===v.id&&q.number.toLowerCase()===m.number.toLowerCase()))throw Error('Quotation number already exists for this vendor.');m.quotationDate=required(d.quotationDate,'Quotation date');if(!validDate(m.quotationDate))throw Error('Enter a valid quotation date.');m.amount=integer(d.amount,1);m.description=required(d.description,'Quotation scope');m.deliveryDays=integer(d.deliveryDays,1,3650);m.creditDays=integer(d.creditDays,0,3650);m.terms=required(d.terms,'Terms');}
 if(k==='award'){const q=suiteRows(s,'quotation',t).find(q=>q.id===d.quotationId);if(!q||!can(s,u,t,'view','vendor_quotation'))throw Error('Select a quotation in this project.');if(suiteRows(s,'award',t).some(a=>a.rfqId===q.rfqId&&suiteStatus(s,a)!=='Rejected'))throw Error('Only one active selection is allowed per work package.');m.quotationId=q.id;m.rfqId=q.rfqId;m.amount=q.amount;m.reason=required(d.reason,'Selection rationale');m.approvalPolicy=2;m.creatorSuperuser=!!u.superuser;}
 if(k==='vendor_feedback'){const v=vendor(d.vendorId);if(!v)throw Error('Select an active vendor.');m.vendorId=v.id;m.vendor=v.name;m.orderId=d.orderId||'';if(m.orderId&&(!order(m.orderId)||order(m.orderId).vendorId!==v.id||!can(s,u,t,'view','work_order')))throw Error('Select a work order belonging to this vendor.');for(const key of ['quality','timeliness','safety','communication'])m[key]=integer(d[key],1,5);m.comments=required(d.comments,'Feedback');m.date=required(d.date,'Feedback date');if(!validDate(m.date))throw Error('Enter a valid date.');}
 if(k==='project_plan'){m.budget=integer(d.budget,1);m.salesTarget=integer(d.salesTarget);m.unitTarget=integer(d.unitTarget,0,1e6);m.startDate=required(d.startDate,'Start date');m.endDate=required(d.endDate,'End date');if(!validDate(m.startDate)||!validDate(m.endDate)||m.endDate<m.startDate)throw Error('Project dates are invalid.');m.monthlyTargets=(d.monthlyTargets||[]).map(x=>{if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(x.month))throw Error('Choose valid target months.');return {month:x.month,cash:integer(x.cash),progress:integer(x.progress,0,100)};});if(new Set(m.monthlyTargets.map(x=>x.month)).size!==m.monthlyTargets.length)throw Error('Target months must be unique.');}
 if(k==='progress'){const o=order(d.orderId);if(!o||orderStatus(s,o)!=='Approved'||!can(s,u,t,'view','work_order'))throw Error('Select an approved work order.');m.orderId=o.id;m.percent=integer(d.percent,0,100);m.date=required(d.date,'Progress date');if(!validDate(m.date))throw Error('Enter a valid date.');m.comments=required(d.comments,'Progress note');}
 if(k==='sale'){if(old&&(s.extensions||[]).some(x=>x.kind==='payment_schedule'&&x.saleId===old.id)&&['amount','unit','date','status'].some(k=>d[k]!==old[k]))throw Error('Scheduled sale value and unit are retained.');m.unit=required(d.unit,'Unit reference');m.customer=required(d.customer,'Customer name');m.status=required(d.status,'Sales stage');if(!['Lead','Reserved','Booked','Cancelled'].includes(m.status))throw Error('Invalid sales stage.');m.amount=integer(d.amount,1);m.date=required(d.date,'Sales date');if(!validDate(m.date))throw Error('Enter a valid date.');const received=suiteRows(s,'collection',t).filter(x=>x.saleId===m.id).reduce((n,x)=>n+x.amount+(x.tds||0),0);if(received>0&&(m.status!=='Booked'||m.amount<received))throw Error('Collected sales cannot be cancelled or reduced below receipts.');if(suiteRows(s,'sale',t).some(x=>x.id!==m.id&&x.unit.toLowerCase()===m.unit.toLowerCase()&&x.status!=='Cancelled'&&m.status!=='Cancelled'))throw Error('This unit already has an active sales record.');}
 if(k==='collection'){const sale=suiteRows(s,'sale',t).find(x=>x.id===d.saleId&&x.status==='Booked');if(!sale||!can(s,u,t,'view','sale'))throw Error('Select a booked unit sale.');m.saleId=sale.id;m.amount=integer(d.amount,1);m.tds=integer(d.tds??0);m.mode=String(d.mode||'');m.bank=String(d.bank||'');m.date=required(d.date,'Receipt date');if(!validDate(m.date)||m.date<sale.date)throw Error('Receipt date must be on or after sale date.');m.reference=required(d.reference,'Receipt reference');m.remarks=String(d.remarks||'').trim();if(suiteRows(s,'collection',t).some(x=>x.id!==m.id&&x.reference.toLowerCase()===m.reference.toLowerCase()))throw Error('Receipt reference already exists.');if(suiteRows(s,'collection',t).filter(x=>x.id!==m.id&&x.saleId===sale.id).reduce((n,x)=>n+x.amount+(x.tds||0),0)+m.amount+m.tds>sale.amount)throw Error('Collections cannot exceed the booked sale value.');}
 return m;
}
export function workContract(s,u,t,d){requireEdit(s,u,t,'work_order',['quotation','contract']);const q=suiteRows(s,'quotation',t).find(q=>q.id===d.quotationId),a=suiteRows(s,'award',t).find(a=>a.quotationId===q?.id&&suiteStatus(s,a)==='Approved'),r=suiteRows(s,'rfq',t).find(r=>r.id===q?.rfqId);if(!q||!a||!r||!can(s,u,t,'view','vendor_quotation'))throw Error('An approved selected quotation ID is mandatory.');if(q.vendorId!==d.vendorId||s.orders.some(o=>o.quotationId===q.id))throw Error('Choose the selected vendor and an unused approved quotation.');if(d.base>q.amount)throw Error('Work-order starting value cannot exceed its selected quotation.');const contractType=r.contractType;if(contractType==='Material construction'){if(!d.boq?.name||!d.boq?.base64||!d.boq?.signed)throw Error('Attach the signed BOQ for material construction.');let raw;try{raw=atob(d.boq.base64);}catch{throw Error('Invalid BOQ file.');}if(d.boq.name.length>180||raw.length===0||raw.length>1048576||!(raw.startsWith('%PDF-')||raw.startsWith('\x89PNG\r\n\x1a\n')||raw.startsWith('\xff\xd8\xff')))throw Error('BOQ must be a PDF, PNG or JPEG up to 1 MB.');}if(contractType==='Labour'&&d.boq)throw Error('Labour contracts use approved purchase-order links.');if(d.orderDate&&!validDate(d.orderDate))throw Error('Enter a valid work-order date.');return {quotationId:q.id,quotationNumber:q.number,rfqId:r.id,contractType,workflowEnabled:true,approvalPolicy:2,creatorSuperuser:!!u.superuser,orderDate:d.orderDate||stamp().slice(0,10),boq:d.boq?{...d.boq,mime:atob(d.boq.base64).startsWith('%PDF-')?'application/pdf':atob(d.boq.base64).startsWith('\x89PNG')?'image/png':'image/jpeg'}:null};}
export function canSuiteAct(s,u,t,d,a,order=false){const f=order?'work_order':'quotation_selection',events=(order?s.orderEvents:s.suiteEvents).map(e=>({...e,amendmentId:e[order?'orderId':'documentId']})),st=order?orderStatus(s,d):suiteStatus(s,d);if(!can(s,u,t,a,f))return false;if(a==='submit')return st==='Draft'&&(u.superuser||d.createdBy===u.id);if(!u.superuser&&d.createdBy===u.id)return false;if(a==='review')return st==='Review';if(a==='reject')return !['Draft','Approved','Rejected'].includes(st);return a==='approve'&&!!approvalStage(s,u,t,d,events,f);}
export function suiteCommand(s,u,t,kind,d,log){if(kind==='suite-save'){if(!suiteFields[d.recordKind])throw Error('Unknown record type.');const m=suiteRecord(s,u,t,d.recordKind,d),i=s.suiteRecords.findIndex(x=>x.id===m.id);if(i>=0){if(['progress','collection','project_plan','vendor_feedback'].includes(m.kind))throw Error('This history is retained; add a new record or version.');s.suiteRecords[i]=m;}else s.suiteRecords.push(m);log(m.kind+' saved',m.title||m.number||m.unit||m.id);return true;}if(!['suite-transition','order-transition'].includes(kind))return false;const isOrder=kind==='order-transition',record=(isOrder?s.orders:s.suiteRecords).find(x=>x.id===d.id&&x.tenantId===t&&(isOrder||x.kind==='award'));if(!record)throw Error('Approval record not found.');if(isOrder&&record.contractType==='Labour'&&d.action==='approve'&&!s.purchaseOrders.some(p=>p.orderId===record.id&&poStatus(s,p)==='Approved'))throw Error('Approve a purchase order linked to this labour work order first.');const f=isOrder?'work_order':'quotation_selection',ev=isOrder?s.orderEvents:s.suiteEvents;const tmp={...s,orders:[{id:record.id,tenantId:t,base:0,number:record.id,formId:f}],amendments:[{...record,orderId:record.id,delta:record.base||record.amount}],events:ev.map(e=>({...e,amendmentId:e[isOrder?'orderId':'documentId']})),audit:[]};let e=transition(tmp,u,t,record.id,d.action);delete e.amendmentId;ev.push({...e,[isOrder?'orderId':'documentId']:record.id});log((isOrder?'Work order':'Quotation selection')+' '+d.action,record.number||record.id);return true;}
export function comparisons(s,rfq){return suiteRows(s,'quotation').filter(q=>q.rfqId===rfq.id).map(q=>{const {score,quality,experience,...bid}=q;return bid;});}
export function redactSuite(s,u){s.suiteRecords=(s.suiteRecords||[]).filter(d=>can(s,u,d.tenantId,'view',formForKind(d.kind))).map(d=>{const f=formForKind(d.kind);redactMetadata(s,u,d.tenantId,f,d);const mask={amount:['amount','tds','budget','salesTarget','monthlyTargets'],description:['description','title'],reference:['referenceOrderId','quotationId','rfqId','orderId','saleId','reference'],reason:['reason'],vendor:['vendor','vendorId'],terms:['deliveryDays','creditDays','terms'],ratings:['quality','experience','timeliness','safety','communication'],comments:['comments'],dates:['date','quotationDate','startDate','endDate'],targets:['unitTarget','monthlyTargets'],progress:['percent'],customer:['customer'],unit:['unit'],status:['status'],weights:['weights'],remarks:['remarks']};for(const [field,keys]of Object.entries(mask))if(fieldAccess(s,u,d.tenantId,field,f)==='hidden')for(const k of keys)delete d[k];return d;});s.suiteEvents=(s.suiteEvents||[]).filter(e=>s.suiteRecords.some(d=>d.id===e.documentId));s.orderEvents=(s.orderEvents||[]).filter(e=>s.orders.some(o=>o.id===e.orderId&&can(s,u,o.tenantId,'view','work_order')));}
