import {fieldAccess,can} from './domain.js';
import {poStatus} from './procurement.js';
export const workOrderFields=['amount','description','reason','unit','period','quantity','purchase_reference'];
export function validDate(value){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value).toISOString().slice(0,10)===value;}
export function workDetails(s,u,t,d){
let items,total=d.base;
if(d.items!==undefined){if(!Array.isArray(d.items)||!d.items.length||d.items.length>100)throw Error('Add 1–100 work-order items.');if(['quantity','unit','period'].some(k=>fieldAccess(s,u,t,k)!=='edit'))throw Error('Item field editing permissions are required.');items=d.items.map(item=>{const {description,unit,startDate,endDate,quantityMilli,rate}=item;if(!description?.trim()||!unit?.trim()||!validDate(startDate)||!validDate(endDate)||startDate>endDate)throw Error('Each item needs a description, unit and valid start/end dates.');if(!Number.isSafeInteger(quantityMilli)||quantityMilli<=0||quantityMilli>1e9||!Number.isSafeInteger(rate)||rate<0||rate>1e11)throw Error('Enter valid item quantities and non-negative rates.');const amount=Number((BigInt(quantityMilli)*BigInt(rate)+500n)/1000n);return {description:description.trim(),unit:unit.trim(),startDate,endDate,quantityMilli,rate,amount};});total=items.reduce((n,i)=>n+i.amount,0);if(total>1e14)throw Error('Work-order total exceeds the supported range.');if(d.base!=null&&d.base!==total)throw Error('Work-order total must equal its item amounts.');}
let reference={};if(d.purchaseOrderId){if(fieldAccess(s,u,t,'purchase_reference')!=='edit'||!can(s,u,t,'view','purchase_order')||fieldAccess(s,u,t,'order_date','purchase_order')==='hidden')throw Error('Purchase-order reference editing permission is required.');const po=s.purchaseOrders.find(p=>p.id===d.purchaseOrderId&&p.tenantId===t&&poStatus(s,p)==='Approved');if(!po)throw Error('Select an approved purchase order in this project.');reference={purchaseOrderId:po.id,purchaseOrderNumber:po.number,purchaseOrderDate:po.orderDate||po.createdAt.slice(0,10)};}
return {base:total,...(items?{items}:{}),...reference};
}
export function redactWorkDetails(s,u,o){for(const i of o.items||[]){if(fieldAccess(s,u,o.tenantId,'amount')==='hidden'){delete i.rate;delete i.amount;}if(fieldAccess(s,u,o.tenantId,'description')==='hidden')delete i.description;if(fieldAccess(s,u,o.tenantId,'quantity')==='hidden')delete i.quantityMilli;if(fieldAccess(s,u,o.tenantId,'unit')==='hidden')delete i.unit;if(fieldAccess(s,u,o.tenantId,'period')==='hidden'){delete i.startDate;delete i.endDate;}}if(fieldAccess(s,u,o.tenantId,'purchase_reference')==='hidden'||!can(s,u,o.tenantId,'view','purchase_order')){delete o.purchaseOrderId;delete o.purchaseOrderNumber;delete o.purchaseOrderDate;}if(fieldAccess(s,u,o.tenantId,'order_date','purchase_order')==='hidden')delete o.purchaseOrderDate;}
